// =============================================================================
// runtime/runtime.hpp — Runtime type definitions for generated C++ code
// =============================================================================
// Every file generated by the compiler includes this header.
// Named runtime.hpp (not types.hpp) to avoid colliding with the compiler's
// own types.hpp (the semantic type system).
// =============================================================================

#pragma once

#include <cstdint>
#include <cstddef>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Slice — non-owning view over a contiguous array of elements.
// Generated slice expressions produce: Slice{ ptr, len }
// ---------------------------------------------------------------------------
struct Slice {
    void*  ptr = nullptr;
    size_t len = 0;
};

// Typed element access helpers (generated code casts through these)
template<typename T> inline T& slice_get(Slice s, size_t i) {
    return reinterpret_cast<T*>(s.ptr)[i];
}

// Bounds-checked index (debug builds only)
#ifdef NDEBUG
#  define SLICE_IDX(T, s, i)  (reinterpret_cast<T*>((s).ptr)[(i)])
#else
#  define SLICE_IDX(T, s, i) \
    ( (static_cast<size_t>(i) < (s).len) \
        ? reinterpret_cast<T*>((s).ptr)[(i)] \
        : (mem_panic("slice index out of bounds"), *reinterpret_cast<T*>(nullptr)) )
#endif

// ---------------------------------------------------------------------------
// Memory helpers
// ---------------------------------------------------------------------------
inline void* mem_alloc(size_t n) {
    void* p = std::malloc(n);
    if (!p) { std::fprintf(stderr, "panic: out of memory\n"); std::abort(); }
    return p;
}
inline void  mem_free(void* p)                          { std::free(p); }
inline void* mem_copy(void* d, const void* s, size_t n) { return std::memcpy(d, s, n); }
inline void* mem_zero(void* p, size_t n)                { return std::memset(p, 0, n); }
[[noreturn]] inline void mem_panic(const char* msg) {
    std::fprintf(stderr, "panic: %s\n", msg);
    std::abort();
}

// ---------------------------------------------------------------------------
// string  →  std::string      (from <string>)
// [dynamic]T  →  std::vector<T>  (from <vector>)
//
// No custom wrappers needed — the compiler emits std:: types directly:
//
//   string literal   "hello"    →  std::string{"hello"}
//   string type                 →  std::string
//   len(s)                      →  (s).size()
//   to_cstr(s)                  →  (s).c_str()
//   from_cstr(cs)               →  std::string(cs)
//
//   [dynamic]T type             →  std::vector<T>
//   append(&arr, val)           →  arr.push_back(val)
//   len(arr)                    →  arr.size()
//   cap(arr)                    →  arr.capacity()
//   reserve(&arr, n)            →  arr.reserve(n)
//   delete_dyn(&arr)            →  (arr.clear(), arr.shrink_to_fit())
// ---------------------------------------------------------------------------
