// =============================================================================
// codegen/codegen.cpp
// =============================================================================

#include "../codegen/codegen.hpp"

#include "../frontend/ast.hpp"       // must precede tok_defs.hpp
#include "../frontend/tok_defs.hpp"  // stable TOK_* constants

#include <cassert>
#include <unordered_set>

namespace ZedLang {

// Static member for HashAssertTopDecl::name()
const std::string HashAssertTopDecl::EMPTY_NAME = "";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
void CodeGen::generate(Program* prog) {
    emit_preamble();
    emit_.blank();
    emit_cimports(prog);

    // For each imported module: emit its cimports, struct typedefs+defs,
    // and proc forward declarations so the generated .cpp is self-contained.
    for (Program* imp : imported_programs_) {
        emit_cimports(imp);
        emit_.comment("--- imported from " + std::string(imp->decls[0]->range.begin.file) + " ---");
        // struct typedefs
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::STRUCT) {
                auto* sd = static_cast<StructDecl*>(d);
                const std::string safe = c_safe_name(sd->struct_name);
                emit_.line("typedef struct " + safe + " " + safe + ";");
            }
        }
        emit_.blank();
        // struct definitions
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::STRUCT)
                emit_struct_def(static_cast<StructDecl*>(d));
        }
        // proc forward declarations
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::PROC)
                emit_proc_decl(static_cast<ProcDecl*>(d));
        }
        emit_.blank();
    }

    emit_enum_decls(prog);
    emit_.blank();
    emit_forward_decls(prog);
    emit_.blank();
    emit_struct_defs(prog);
    emit_.blank();
    emit_global_consts(prog);
    emit_.blank();
    emit_global_vars(prog);
    emit_.blank();
    emit_proc_defs(prog);
}

// ---------------------------------------------------------------------------
// Preamble
// ---------------------------------------------------------------------------
void CodeGen::emit_preamble() {
    emit_.comment("Generated by Zed Lang — DO NOT EDIT !!");
    emit_.line("#include \"runtime.hpp\"");
    emit_.blank();
}   

void CodeGen::emit_cimports(Program* prog) {
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::CIMPORT) continue;
        auto* ci = static_cast<CImportDecl*>(d);
        emit_.line("#include \"" + ci->path + "\"");
    }
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Forward declarations
// ---------------------------------------------------------------------------
void CodeGen::emit_forward_decls(Program* prog) {
    emit_.comment("--- Forward Declarations ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::STRUCT) {
            auto* sd = static_cast<StructDecl*>(d);
            const std::string safe = c_safe_name(sd->struct_name);
            emit_.line("typedef struct " + safe + " " + safe + ";");
        } else if (d->kind() == Decl::UNION_DECL) {
            auto* ud = static_cast<UnionDecl*>(d);
            const std::string safe = c_safe_name(ud->union_name);
            emit_.line("typedef union " + safe + " " + safe + ";");
        }
    }
    emit_.blank();
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::PROC)
            emit_proc_decl(static_cast<ProcDecl*>(d));
    }
}

// ---------------------------------------------------------------------------
// Struct definitions
// ---------------------------------------------------------------------------
void CodeGen::emit_struct_defs(Program* prog) {
    emit_.comment("--- Struct / Union Definitions ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::STRUCT)
            emit_struct_def(static_cast<StructDecl*>(d));
        else if (d->kind() == Decl::UNION_DECL)
            emit_union_def(static_cast<UnionDecl*>(d));
    }
}

void CodeGen::emit_union_def(UnionDecl* ud) {
    emit_.emit_indent();
    emit_.emit("union " + c_safe_name(ud->union_name));
    emit_.open_brace();
    sem::StructType* st = static_cast<sem::StructType*>(
        tc_.sym_ref().lookup_struct(ud->union_name));
    if (st) {
        for (const auto& f : st->fields) {
            emit_.emit_indent();
            emit_var_decl(f.type, f.name);
            emit_.emit(";\n");
        }
    }
    emit_.close_brace_semi();
    emit_.blank();
}

void CodeGen::emit_enum_decls(Program* prog) {
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::ENUM_DECL) continue;
        auto* ed = static_cast<EnumDecl*>(d);
        emit_.line("enum class " + ed->enum_name + " : int32_t {");
        emit_.indent();
        int64_t next = 0;
        for (const auto& v : ed->variants) {
            int64_t val = next;
            if (v.value) {
                if (auto* lit = dynamic_cast<LitExpr*>(v.value))
                    if (lit->lit_kind == LitExpr::INT) val = (int64_t)lit->int_val;
            }
            emit_.line(v.name + " = " + std::to_string(val) + ",");
            next = val + 1;
        }
        emit_.dedent();
        emit_.line("};");
        emit_.blank();
    }
}

void CodeGen::emit_struct_def(StructDecl* sd) {
    emit_.emit_indent();
    emit_.emit("struct " + c_safe_name(sd->struct_name));
    emit_.open_brace();
    sem::StructType* st = static_cast<sem::StructType*>(
        tc_.sym_ref().lookup_struct(sd->struct_name));
    if (st) {
        for (const auto& f : st->fields) {
            emit_.emit_indent();
            emit_var_decl(f.type, f.name);
            emit_.emit(";\n");
        }
    }
    emit_.close_brace_semi();
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Global constants
// ---------------------------------------------------------------------------

void CodeGen::emit_global_consts(Program *prog) {
    emit_.comment("--- Global Constants & Static Assertions ---");
    bool any = false;
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::CONST) {
            emit_global_const(static_cast<ConstDecl*>(d));
            any = true;
        } else if (d->kind() == Decl::HASH_ASSERT_DECL) {
            auto* ha = static_cast<HashAssertTopDecl*>(d);
            emit_.begin_line("static_assert(");
            emit_expr(ha->cond);
            emit_.emit(", \"#assert at ");
            emit_.emit(ha->range.begin.to_string());
            emit_.emit("\");\n");
            any = true;
        }
    }
    if (any) emit_.blank();
}

void CodeGen::emit_global_const(ConstDecl *cd) {
    TypeRef ty = tc_.type_of(cd->value);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    const std::string safe = c_safe_name(cd->const_name);
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        // C constant/enum — emit as auto const
        emit_.emit("const auto " + safe);
        if (cd->value) { emit_.emit(" = "); emit_expr(cd->value); }
        emit_.emit(";\n");
        return;
    }
    // add 'const' is the type is not already const-qualified (e.g. pointer types, const char*, etc)
    if (!ty->is_cstr()) emit_.emit("const ");
    emit_c_type(ty);
    emit_.emit(" " + safe);
    if (cd->value) {
        emit_.emit(" = ");
        emit_expr(cd->value);
    }
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Global variables
// ---------------------------------------------------------------------------
void CodeGen::emit_global_vars(Program *prog) {
    emit_.comment("--- Global Variables ---");
    bool any = false;
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::VAR) continue;
        emit_global_var(static_cast<VarDecl*>(d));
        any = true;
    }
    if (any) emit_.blank();
}

void CodeGen::emit_global_var(VarDecl* vd) {
    TypeRef ty = tc_.type_of_decl(vd);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    const std::string safe = c_safe_name(vd->var_name);
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        std::string cname = (ty->kind == SemanticType::Kind::FOREIGN_NAMED)
            ? static_cast<sem::ForeignNamedType*>(ty)->name
            : "auto";
        emit_.emit(cname + " " + safe);
        if (vd->init) { emit_.emit(" = "); emit_expr(vd->init); }
        else emit_.emit(" = {}");
        emit_.emit(";\n");
        return;
    }
    emit_var_decl(ty, vd->var_name);   // emit_var_decl sanitizes name internally
    if (vd->init) {
        emit_.emit(" = ");
        if (dynamic_cast<ArrayInitExpr*>(vd->init) && ty->is_array()) {
            auto* at = static_cast<sem::ArrayType*>(ty);
            emit_.emit("(");
            emit_c_type(at->elem);
            emit_.emit("[" + std::to_string(at->count) + "])");
        }
        emit_expr(vd->init);
    } else {
        emit_.emit(" = {}");
    }
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Procedure forward declaration
// ---------------------------------------------------------------------------
// Emit C struct for multi-return if not already emitted
void CodeGen::emit_multi_ret_struct(const std::string& name, sem::TupleType* tt) {
    std::string sname = "__ret_" + name;
    if (emitted_ret_structs_.count(sname)) return;
    emitted_ret_structs_.insert(sname);
    emit_.emit("typedef struct { ");
    for (size_t i = 0; i < tt->elems.size(); ++i) {
        emit_var_decl(tt->elems[i], "_" + std::to_string(i));
        emit_.emit("; ");
    }
    emit_.emit("} " + sname + ";\n");
}

void CodeGen::emit_proc_decl(ProcDecl *pd) {
    emit_.comment("--- Procedure Forward Declarations ---");
    TypeRef ty = tc_.sym_ref().lookup(pd->proc_name) ?
                 tc_.sym_ref().lookup(pd->proc_name)->type : nullptr;
    if (!ty || !ty->is_proc()) return;
    auto* pt = static_cast<sem::ProcType*>(ty);

    // collect_globals may store return_type=nullptr for multi-return procs,
    // leaving resolution to check_proc_body. Fall back to the AST list.
    const bool is_multi_ret = (pt->return_type && pt->return_type->is_tuple())
                               || !pd->return_types.empty();

    // Emit the return struct typedef if needed
    if (is_multi_ret) {
        if (pt->return_type && pt->return_type->is_tuple()) {
            emit_multi_ret_struct(pd->proc_name,
                static_cast<sem::TupleType*>(pt->return_type));
        } else {
            // Symbol has null return_type — build struct from AST return type list
            std::string sname = "__ret_" + pd->proc_name;
            if (!emitted_ret_structs_.count(sname)) {
                emitted_ret_structs_.insert(sname);
                emit_.emit("typedef struct { ");
                for (size_t i = 0; i < pd->return_types.size(); ++i) {
                    emit_var_decl(tc_.resolve(pd->return_types[i]),
                                  "_" + std::to_string(i));
                    emit_.emit("; ");
                }
                emit_.emit("} " + sname + ";\n");
            }
        }
    }

    emit_.emit_indent();
    current_proc_name_ = pd->proc_name;   // for multi-return emit_return
    if (is_multi_ret)
        emit_.emit("__ret_" + pd->proc_name);
    else if (pt->return_type) emit_c_type(pt->return_type);
    else emit_.emit("void");
    emit_.emit(" " + c_safe_name(pd->proc_name) + "(");

    bool first = true;
    for (const auto& p : pt->params) {
        if (!first) emit_.emit(", ");
        emit_var_decl(p.type, p.name);
        first = false;
    }
    if (pt->params.empty() && !pt->is_variadic) emit_.emit("void");
    if (pt->is_variadic) { if (!first) emit_.emit(", "); emit_.emit("..."); }
    emit_.emit(");\n");
}

// ---------------------------------------------------------------------------
// Procedure definitions
// ---------------------------------------------------------------------------
void CodeGen::emit_proc_defs(Program* prog) {
    emit_.comment("--- Procedure Definitions ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::PROC)
            emit_proc_def(static_cast<ProcDecl*>(d));
    }
}

void CodeGen::emit_proc_def(ProcDecl* pd) {
    if (!pd->body) return;

    // Reset per-proc tmp counter so multi-return call names are unique within
    // each proc body even when the same callee is called more than once.
    tmp_counter_ = 0;

    TypeRef ty = tc_.sym_ref().lookup(pd->proc_name) ?
                 tc_.sym_ref().lookup(pd->proc_name)->type : nullptr;
    if (!ty || !ty->is_proc()) return;
    auto* pt = static_cast<sem::ProcType*>(ty);

    // Must be set before body so emit_return/emit_or_return use the correct struct name
    current_proc_name_         = pd->proc_name;
    current_proc_return_names_ = pd->return_names;

    // collect_globals may store return_type=nullptr for multi-return procs,
    // leaving resolution to check_proc_body. Fall back to the AST list.
    const bool is_multi_ret = (pt->return_type && pt->return_type->is_tuple())
                               || !pd->return_types.empty();

    // Signature
    if (is_multi_ret)
        emit_.emit("__ret_" + pd->proc_name);
    else if (pt->return_type) emit_c_type(pt->return_type);
    else emit_.emit("void");
    emit_.emit(" " + c_safe_name(pd->proc_name) + "(");

    bool first = true;
    size_t pi = 0;
    for (const ParamGroup& pg : pd->params) {
        if (pg.is_vararg_sentinel) continue;
        TypeRef pty = pt->params[pi].type;
        for (const std::string& pname : pg.names) {
            if (!first) emit_.emit(", ");
            emit_var_decl(pty, pname);
            first = false;
            pi++;
        }
    }
    if (pt->params.empty() && !pt->is_variadic) emit_.emit("void");
    if (pt->is_variadic) { if (!first) emit_.emit(", "); emit_.emit("..."); }
    emit_.emit(")");

    // Named return variables are zero-initialized at the top of the body.
    if (!pd->return_names.empty() && pt->return_type && pt->return_type->is_tuple()) {
        auto* tt = static_cast<sem::TupleType*>(pt->return_type);
        emit_.emit(" {\n");
        emit_.indent();
        for (size_t i = 0; i < pd->return_names.size() && i < tt->elems.size(); ++i) {
            emit_.emit_indent();
            emit_var_decl(tt->elems[i], pd->return_names[i]);
            emit_.emit(" = {};\n");
        }
        emit_block(pd->body, false);
        emit_.dedent();
        emit_.emit_indent();
        emit_.emit("}\n");
    } else {
        emit_block(pd->body, true);
    }
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Statements
// ---------------------------------------------------------------------------
void CodeGen::emit_stmt(Stmt* s) {
    switch (s->kind()) {
        case Stmt::BLOCK:     emit_block(static_cast<BlockStmt*>(s));          break;
        case Stmt::IF:        emit_if(static_cast<IfStmt*>(s));                break;
        case Stmt::LOOP:      emit_loop(static_cast<LoopStmt*>(s));            break;
        case Stmt::RETURN:    emit_return(static_cast<ReturnStmt*>(s));        break;
        case Stmt::ASSIGN:    emit_assign(static_cast<AssignStmt*>(s));        break;
        case Stmt::EXPR:      emit_expr_stmt(static_cast<ExprStmt*>(s));       break;
        case Stmt::DECL_STMT: emit_decl_stmt(static_cast<DeclStmt*>(s));      break;
        case Stmt::BREAK:     emit_.line("break;");                            break;
        case Stmt::CONTINUE:  emit_.line("continue;");                         break;
        case Stmt::BREAK_LABEL: {
            auto* s2 = static_cast<LabeledBreakStmt*>(s);
            emit_.line("goto __break_" + s2->label + ";");
            break;
        }
        case Stmt::CONTINUE_LABEL: {
            auto* s2 = static_cast<LabeledContinueStmt*>(s);
            emit_.line("goto __continue_" + s2->label + ";");
            break;
        }
        case Stmt::FOR_RANGE:      emit_for_range(static_cast<ForRangeStmt*>(s));          break;
        case Stmt::FOR_EACH:       emit_for_each(static_cast<ForEachStmt*>(s));            break;
        case Stmt::DEFER:          /* deferred — emitted at return/block end */             break;
        case Stmt::MATCH:          emit_match(static_cast<MatchStmt*>(s));                  break;
        case Stmt::WHEN:           emit_when(static_cast<WhenStmt*>(s));                    break;
        case Stmt::COMPOUND_ASSIGN:emit_compound_assign(static_cast<CompoundAssignStmt*>(s)); break;
        case Stmt::HASH_ASSERT:    emit_hash_assert(static_cast<HashAssertStmt*>(s));        break;
        case Stmt::MULTI_DECL:     emit_multi_decl(static_cast<MultiDeclStmt*>(s));          break;
        case Stmt::MULTI_ASSIGN:   emit_multi_assign(static_cast<MultiAssignStmt*>(s));       break;
    }
}

// Collect defer stmts in immediate scope of block (not nested)
static std::vector<Stmt*> collect_defers(BlockStmt* b) {
    std::vector<Stmt*> defers;
    for (Stmt* s : b->stmts)
        if (s->kind() == Stmt::DEFER)
            defers.push_back(static_cast<DeferStmt*>(s)->inner);
    std::reverse(defers.begin(), defers.end()); // LIFO
    return defers;
}

void CodeGen::emit_block(BlockStmt* b, bool own_braces) {
    if (own_braces) {
        emit_.emit(" {\n");
        emit_.indent();
    }
    auto defers = collect_defers(b);
    bool returned = false;
    for (Stmt* s : b->stmts) {
        if (!defers.empty()) {
            if (s->kind() == Stmt::RETURN) {
                // Flush defers LIFO before the return
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
                returned = true;
            } else if (s->kind() == Stmt::BREAK || s->kind() == Stmt::CONTINUE) {
                // Also flush before break/continue
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
            }
        }
        emit_stmt(s);
    }
    // Fall-through end of block: flush if we didn't already return
    if (!returned) {
        for (Stmt* d : defers) {
            emit_.emit_indent();
            emit_expr(static_cast<ExprStmt*>(d)->expr);
            emit_.emit(";\n");
        }
    }
    if (own_braces) {
        emit_.dedent();
        emit_.emit_indent();
        emit_.emit("}\n");
    }
}

void CodeGen::emit_if(IfStmt* s) {
    emit_.begin_line("if (");
    emit_expr(s->cond);
    emit_.emit(")");
    emit_block(s->then_block, true);

    for (auto& [econd, eblk] : s->else_ifs) {
        emit_.begin_line("else if (");
        emit_expr(econd);
        emit_.emit(")");
        emit_block(eblk, true);
    }

    if (s->else_block) {
        emit_.begin_line("else");
        emit_block(s->else_block, true);
    }
}

// ---------------------------------------------------------------------------
// for_range: for i in lo..<hi { }  →  for (auto i = lo; i < hi; i += step)
// ---------------------------------------------------------------------------
void CodeGen::emit_for_range(ForRangeStmt* s) {
    const std::string safe_var = c_safe_name(s->var);
    emit_.begin_line("for (auto " + safe_var + " = ");
    emit_expr(s->lo);
    emit_.emit("; " + safe_var + (s->inclusive ? " <= " : " < "));
    emit_expr(s->hi);
    emit_.emit("; " + safe_var + " += ");
    if (s->step_expr) emit_expr(s->step_expr);
    else emit_.emit("1");
    emit_.emit(")");

    if (s->label.empty()) {
        emit_block(s->body, true);
        return;
    }

    // Labeled: manually emit block so we can inject goto labels
    emit_.emit(" {\n");
    emit_.indent();
    for (Stmt* st : s->body->stmts) emit_stmt(st);
    emit_.line("__continue_" + s->label + ":;");
    emit_.dedent();
    emit_.line("}");
    emit_.line("__break_" + s->label + ":;");
}

// ---------------------------------------------------------------------------
// emit_for_each — for item in coll { }  /  for i, item in coll { }
// Expands to a C++ indexed for loop so both index and element are available.
// Works for fixed arrays, slices, dynamic arrays, and strings.
// ---------------------------------------------------------------------------
void CodeGen::emit_for_each(ForEachStmt* s) {
    TypeRef cty = tc_.type_of(s->collection);

    // Emit the collection expression into a const reference to avoid
    // re-evaluating a complex expression multiple times.
    const std::string coll_tmp = "_zed_coll_" + c_safe_name(s->value_var) + "_";
    emit_.begin_line("{\n");
    emit_.indent();

    // Store collection in a temp
    emit_.emit_indent();
    emit_.emit("auto& " + coll_tmp + " = ");
    emit_expr(s->collection);
    emit_.emit(";\n");

    // Length expression
    std::string len_expr;
    if (cty && cty->is_array())
        len_expr = std::to_string(static_cast<sem::ArrayType*>(cty)->count);
    else if (cty && cty->is_dyn_array())
        len_expr = coll_tmp + ".size()";
    else if (cty && cty->is_string())
        len_expr = coll_tmp + ".size()";
    else
        len_expr = coll_tmp + ".len";  // Slice

    const std::string idx_var = s->index_var.empty()
        ? ("_zed_i_" + c_safe_name(s->value_var) + "_")
        : c_safe_name(s->index_var);

    emit_.emit_indent();
    emit_.emit("for (int64_t " + idx_var + " = 0; "
               + idx_var + " < (int64_t)(" + len_expr + "); "
               + "++" + idx_var + ") {\n");
    emit_.indent();

    // Element variable
    const std::string val_var = c_safe_name(s->value_var);
    emit_.emit_indent();
    if (cty && cty->is_slice()) {
        auto* st = static_cast<sem::SliceType*>(cty);
        emit_.emit("auto& " + val_var + " = SLICE_IDX(");
        emit_c_type(st->elem);
        emit_.emit(", " + coll_tmp + ", " + idx_var + ");\n");
    } else if (cty && cty->is_string()) {
        emit_.emit("uint8_t " + val_var + " = (uint8_t)" + coll_tmp + "[" + idx_var + "];\n");
    } else {
        emit_.emit("auto& " + val_var + " = " + coll_tmp + "[" + idx_var + "];\n");
    }

    // Body statements
    for (Stmt* st : s->body->stmts) emit_stmt(st);

    if (!s->label.empty())
        emit_.line("__continue_" + s->label + ":;");

    emit_.dedent();
    emit_.line("}");
    if (!s->label.empty())
        emit_.line("__break_" + s->label + ":;");
    emit_.dedent();
    emit_.line("}");
}

// ---------------------------------------------------------------------------
// match:  match val { case X { } case { } }  →  switch(val) { case X: { } break; default: { } }
// ---------------------------------------------------------------------------
void CodeGen::emit_match(MatchStmt* s) {
    TypeRef vty = tc_.type_of(s->value);
    emit_.begin_line("switch (");
    emit_expr(s->value);
    emit_.emit(") {\n");
    emit_.indent();
    for (auto& mc : s->cases) {
        if (mc.value) {
            emit_.emit_indent();
            emit_.emit("case ");
            // Dot-shorthand: bare IdentExpr annotated with enum type by type checker
            if (mc.value->kind() == Expr::IDENT && vty && vty->is_enum()) {
                auto* id = static_cast<IdentExpr*>(mc.value);
                auto* et = static_cast<sem::EnumType*>(vty);
                if (et->find_variant(id->name)) {
                    // enum class requires qualified name: Direction::WEST not just WEST
                    emit_.emit(c_safe_name(et->name) + "::" + id->name);
                } else {
                    emit_expr(mc.value);
                }
            } else {
                emit_expr(mc.value);
            }
            emit_.emit(":");
        } else {
            emit_.begin_line("default:");
        }
        emit_block(mc.body, true);
        emit_.line("break;");
    }
    emit_.dedent();
    emit_.line("}");
}

// ---------------------------------------------------------------------------
// when:  compile-time conditional → emit only the matching branch
// For now we emit #if 0 / #else approach; simplest: emit all branches guarded
// by constexpr if so C++ compiler trims them.
// ---------------------------------------------------------------------------
void CodeGen::emit_when(WhenStmt* s) {
    emit_.begin_line("if constexpr (");
    emit_expr(s->cond);
    emit_.emit(")");
    emit_block(s->then_block, true);
    for (auto& [ec, eb] : s->else_whens) {
        emit_.begin_line("else if constexpr (");
        emit_expr(ec);
        emit_.emit(")");
        emit_block(eb, true);
    }
    if (s->else_block) {
        emit_.begin_line("else");
        emit_block(s->else_block, true);
    }
}

// ---------------------------------------------------------------------------
// compound assign
// ---------------------------------------------------------------------------
void CodeGen::emit_compound_assign(CompoundAssignStmt* s) {
    emit_.emit_indent();
    emit_expr(s->lvalue);
    switch (s->op) {
        case TOK_PLUS:    emit_.emit(" += "); break;
        case TOK_MINUS:   emit_.emit(" -= "); break;
        case TOK_STAR:    emit_.emit(" *= "); break;
        case TOK_SLASH:   emit_.emit(" /= "); break;
        case TOK_PERCENT: emit_.emit(" %= "); break;
        case TOK_AMP:     emit_.emit(" &= "); break;
        case TOK_PIPE:    emit_.emit(" |= "); break;
        case TOK_XOR:     emit_.emit(" ^= "); break;
        case TOK_SHL:     emit_.emit(" <<= "); break;
        case TOK_SHR:     emit_.emit(" >>= "); break;
        default:          emit_.emit(" += "); break;
    }
    emit_expr(s->rhs);
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// #assert  →  static_assert(expr, "file:line: #assert failed")
// ---------------------------------------------------------------------------
void CodeGen::emit_hash_assert(HashAssertStmt* s) {
    std::string msg = std::string(s->range.begin.file ? s->range.begin.file : "?")
                    + ":" + std::to_string(s->range.begin.line)
                    + ": #assert failed";
    emit_.emit_indent();
    emit_.emit("static_assert(");
    emit_expr(s->cond);
    emit_.emit(", \"" + msg + "\");\n");
}

// ---------------------------------------------------------------------------
// for { } / for cond { }  (infinite and while-loop forms)
// ---------------------------------------------------------------------------
void CodeGen::emit_loop(LoopStmt* s) {
    if (s->cond) {
        emit_.begin_line("while (");
        emit_expr(s->cond);
        emit_.emit(")");
    } else {
        emit_.begin_line("for (;;)");
    }

    if (s->label.empty()) {
        // No label — delegate entirely to emit_block, which handles defers.
        emit_block(s->body, true);
        return;
    }

    // Labeled loop: emit the block manually so we can inject the
    // __continue label inside the closing brace (LIFO, after defers).
    emit_.emit(" {\n");
    emit_.indent();

    auto defers = collect_defers(s->body);
    bool returned = false;
    for (Stmt* st : s->body->stmts) {
        if (!defers.empty()) {
            if (st->kind() == Stmt::RETURN) {
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
                returned = true;
            } else if (st->kind() == Stmt::BREAK || st->kind() == Stmt::CONTINUE
                    || st->kind() == Stmt::BREAK_LABEL || st->kind() == Stmt::CONTINUE_LABEL) {
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
            }
        }
        emit_stmt(st);
    }
    if (!returned) {
        for (Stmt* d : defers) {
            emit_.emit_indent();
            emit_expr(static_cast<ExprStmt*>(d)->expr);
            emit_.emit(";\n");
        }
    }
    // continue-label goes at end of body (before closing brace)
    emit_.line("__continue_" + s->label + ":;");
    emit_.dedent();
    emit_.emit_indent();
    emit_.emit("}\n");
    // break-label goes after the loop
    emit_.line("__break_" + s->label + ":;");
}

void CodeGen::emit_return(ReturnStmt* s) {
    if (s->value) {
        TypeRef vty = tc_.type_of(s->value);
        if (vty && vty->is_tuple()) {
            // Multi-return: build __ret_PROC struct from the tuple elements
            // Walk up to find the enclosing proc name for the struct type
            // We emit: return (__ret_NAME){._0=a, ._1=b}
            // Find the proc name from the current scope
            const std::string& pname = current_proc_name_;
            auto* te = static_cast<TupleExpr*>(s->value);
            emit_.begin_line("return (__ret_" + pname + "){");
            for (size_t i = 0; i < te->elems.size(); ++i) {
                if (i) emit_.emit(", ");
                emit_.emit("._" + std::to_string(i) + "=");
                emit_expr(te->elems[i]);
            }
            emit_.emit("};\n");
        } else {
            emit_.begin_line("return ");
            emit_expr(s->value);
            emit_.emit(";\n");
        }
    } else {
        // Bare 'return' in a named-return proc: collect all named vars into the ret struct.
        if (!current_proc_return_names_.empty()) {
            const std::string& pname = current_proc_name_;
            emit_.begin_line("return (__ret_" + pname + "){");
            for (size_t i = 0; i < current_proc_return_names_.size(); ++i) {
                if (i) emit_.emit(", ");
                emit_.emit("._" + std::to_string(i) + "=" +
                           c_safe_name(current_proc_return_names_[i]));
            }
            emit_.emit("};\n");
        } else {
            emit_.line("return;");
        }
    }
}

void CodeGen::emit_assign(AssignStmt* s) {
    // _ = expr  →  evaluate for side-effects only, discard result
    if (s->lvalue->kind() == Expr::IDENT) {
        auto* id = static_cast<IdentExpr*>(s->lvalue);
        if (id->name == "_") {
            emit_.emit_indent();
            emit_.emit("(void)(");
            emit_expr(s->rhs);
            emit_.emit(");\n");
            return;
        }
    }
    emit_.emit_indent();
    emit_expr(s->lvalue);
    emit_.emit(" = ");
    emit_expr_hint(s->rhs, tc_.type_of(s->lvalue));
    emit_.emit(";\n");
}

void CodeGen::emit_expr_stmt(ExprStmt* s) {
    emit_.emit_indent();
    emit_expr(s->expr);
    emit_.emit(";\n");
}

void CodeGen::emit_decl_stmt(DeclStmt* s) {
    switch (s->decl->kind()) {
        case Decl::VAR:   emit_var_decl_local(static_cast<VarDecl*>(s->decl));   break;
        case Decl::CONST: emit_const_decl_local(static_cast<ConstDecl*>(s->decl)); break;
        default: break;
    }
}

void CodeGen::emit_var_decl_local(VarDecl* vd) {
    // '_' discard: evaluate init for side-effects only, emit nothing if no init
    if (vd->var_name == "_") {
        if (vd->init) {
            emit_.emit_indent();
            emit_.emit("(void)(");
            emit_expr(vd->init);
            emit_.emit(");\n");
        }
        return;
    }
    const std::string safe = c_safe_name(vd->var_name);
    TypeRef ty = tc_.type_of_decl(vd);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        if (ty->kind == SemanticType::Kind::FOREIGN_NAMED) {
            const std::string& cname = static_cast<sem::ForeignNamedType*>(ty)->name;
            if (vd->init) {
                emit_.emit(cname + " " + safe + " = ");
                emit_expr(vd->init);
                emit_.emit(";\n");
            } else {
                emit_.emit(cname + " " + safe + " = {};\n");
            }
        } else if (vd->init) {
            emit_.emit("auto " + safe + " = ");
            emit_expr(vd->init);
            emit_.emit(";\n");
        } else {
            emit_.emit("void* " + safe + " = nullptr;\n");
        }
        return;
    }
    emit_var_decl(ty, vd->var_name);   // emit_var_decl sanitizes name internally
    // Exception: proc types with tuple return must use 'auto' — std::function
    // cannot store a lambda returning a locally-defined struct, and emit_c_type
    // would produce void for the return type.
    if (ty->is_proc()) {
        auto* pt = static_cast<sem::ProcType*>(ty);
        if (pt->return_type && pt->return_type->is_tuple()) {
            emit_.emit_indent();
            emit_.emit("auto " + c_safe_name(vd->var_name));
            if (vd->init) {
                emit_.emit(" = ");
                emit_expr_hint(vd->init, ty);
            }
            emit_.emit(";\n");
            return;
        }
    }
    if (vd->init) {
        emit_.emit(" = ");
        emit_expr_hint(vd->init, ty);
    } else {
        emit_.emit(" = {}");
    }
    emit_.emit(";\n");
}

void CodeGen::emit_const_decl_local(ConstDecl* cd) {
    // Constants become static const local variables in C.
    TypeRef ty = tc_.type_of(cd->value);
    const std::string safe = c_safe_name(cd->const_name);
    if (ty->is_any_foreign()) {
        // C enum value / macro constant — let the C compiler determine the type.
        emit_.begin_line("static const auto ");
        emit_.emit(safe + " = ");
        emit_expr(cd->value);
        emit_.emit(";\n");
        return;
    }
    // cstr maps to "const char*" — don't prepend another "const"
    if (ty->is_cstr())
        emit_.begin_line("static ");
    else
        emit_.begin_line("static const ");
    // Proc types with tuple return must use 'auto' — std::function cannot
    // store a lambda returning a locally-defined struct.
    if (ty->is_proc()) {
        auto* pt = static_cast<sem::ProcType*>(ty);
        if (pt->return_type && pt->return_type->is_tuple()) {
            // Re-emit without the std::function wrapper
            emit_.emit("auto " + c_safe_name(cd->const_name) + " = ");
            emit_expr(cd->value);
            emit_.emit(";\n");
            return;
        }
    }
    emit_var_decl(ty, cd->const_name);  // emit_var_decl sanitizes internally
    emit_.emit(" = ");
    emit_expr(cd->value);
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Expressions
// ---------------------------------------------------------------------------
void CodeGen::emit_expr(Expr* e) {
    switch (e->kind()) {
        case Expr::BINARY:     emit_binary(static_cast<BinaryExpr*>(e));           break;
        case Expr::UNARY:      emit_unary(static_cast<UnaryExpr*>(e));             break;
        case Expr::CALL:       emit_call(static_cast<CallExpr*>(e));               break;
        case Expr::INDEX:      emit_index(static_cast<IndexExpr*>(e));             break;
        case Expr::SLICE:      emit_slice(static_cast<SliceExpr*>(e));             break;
        case Expr::FIELD:      emit_field(static_cast<FieldExpr*>(e));             break;
        case Expr::DEREF:      emit_deref(static_cast<DerefExpr*>(e));             break;
        case Expr::ADDR:       emit_addr(static_cast<AddrExpr*>(e));               break;
        case Expr::CAST:       emit_cast(static_cast<CastExpr*>(e));               break;
        case Expr::LIT:        emit_lit(static_cast<LitExpr*>(e));                 break;
        case Expr::IDENT:      emit_ident(static_cast<IdentExpr*>(e));             break;
        case Expr::STRUCT_LIT: emit_struct_lit(static_cast<StructLitExpr*>(e));    break;
        case Expr::TUPLE:      emit_tuple(static_cast<TupleExpr*>(e));              break;
        case Expr::SIZEOF_EXPR:emit_sizeof(static_cast<SizeofExpr*>(e));            break;
        case Expr::ARRAY_INIT:    emit_array_init(static_cast<ArrayInitExpr*>(e));    break;
        case Expr::BUILTIN_CALL:  emit_builtin_call(static_cast<BuiltinCallExpr*>(e)); break;
        case Expr::OR_RETURN_EXPR:emit_or_return(static_cast<OrReturnExpr*>(e));      break;
        case Expr::PROC_LIT:      emit_proc_lit(static_cast<ProcLitExpr*>(e));        break;
        case Expr::TYPEID_EXPR:   emit_typeid(static_cast<TypeIdExpr*>(e));           break;
    }
}

void CodeGen::emit_expr_hint(Expr* e, TypeRef hint) {
    if (e->kind() == Expr::LIT)
        emit_lit(static_cast<LitExpr*>(e), hint);
    else
        emit_expr(e);
}

void CodeGen::emit_binary(BinaryExpr* e) {
    TypeRef lty = tc_.type_of(e->left);
    TypeRef rty = tc_.type_of(e->right);

    // String concatenation: emit std::string(lhs) + rhs to ensure operator+ works
    if (e->op == TOK_PLUS && lty && rty &&
        (lty->is_string() || lty->is_cstr()) &&
        (rty->is_string() || rty->is_cstr())) {
        emit_.emit("(std::string(");
        emit_expr(e->left);
        emit_.emit(") + std::string(");
        emit_expr(e->right);
        emit_.emit("))");
        return;
    }

    TypeRef operand_ty = lty;
    emit_.emit("(");
    emit_expr_hint(e->left, operand_ty);
    emit_.emit(" " + op_str(e->op) + " ");
    emit_expr_hint(e->right, operand_ty);
    emit_.emit(")");
}

void CodeGen::emit_unary(UnaryExpr* e) {
    emit_.emit("(" + op_str(e->op));
    // Pass the type of the subexpression as a hint so that float literals
    // inside unary minus get the correct suffix: -(0.5f) not -(0.5)
    TypeRef hint = tc_.type_of(e->expr);
    emit_expr_hint(e->expr, hint);
    emit_.emit(")");
}

void CodeGen::emit_call(CallExpr* e) {
    emit_expr(e->callee);
    emit_.emit("(");
    // Look up param types to pass as hints for float literal suffixes
    TypeRef callee_ty = tc_.type_of(e->callee);
    sem::ProcType* pt = (callee_ty && callee_ty->is_proc())
                      ? static_cast<sem::ProcType*>(callee_ty) : nullptr;
    for (size_t i = 0; i < e->args.size(); ++i) {
        if (i > 0) emit_.emit(", ");
        TypeRef hint = (pt && i < pt->params.size()) ? pt->params[i].type : nullptr;
        emit_expr_hint(e->args[i], hint);
    }
    emit_.emit(")");
}

void CodeGen::emit_index(IndexExpr* e) {
    TypeRef bty = tc_.type_of(e->base);

    if (bty->is_slice()) {
        // Slice indexing: SLICE_IDX(ElemType, slice, idx)
        auto* st = static_cast<sem::SliceType*>(bty);
        emit_.emit("SLICE_IDX(");
        emit_c_type(st->elem);
        emit_.emit(", ");
        emit_expr(e->base);
        emit_.emit(", ");
        emit_expr(e->index);
        emit_.emit(")");
    } else if (bty->is_dyn_array()) {
        // Dynamic array (std::vector) — use DYN_IDX for bounds-checked access
        auto* da = static_cast<sem::DynArrayType*>(bty);
        emit_.emit("DYN_IDX(");
        emit_c_type(da->elem);
        emit_.emit(", ");
        emit_expr(e->base);
        emit_.emit(", ");
        emit_expr(e->index);
        emit_.emit(")");
    } else if (bty->is_string()) {
        // string[i] — std::string::operator[] returns char& (lvalue-compatible).
        // No cast here; surrounding context handles the u8 type via the type system.
        emit_.emit("(");
        emit_expr(e->base);
        emit_.emit(")[");
        emit_expr(e->index);
        emit_.emit("]");
    } else {
        // Plain array indexing
        emit_expr(e->base);
        emit_.emit("[");
        emit_expr(e->index);
        emit_.emit("]");
    }
}

void CodeGen::emit_slice(SliceExpr* e) {
    // Produce a Slice struct literal: { .ptr = base + lo, .len = hi - lo }
    TypeRef bty = tc_.type_of(e->base);

    emit_.emit("((Slice){ .ptr = (void*)(");
    if (bty->is_array()) {
        emit_expr(e->base);
    } else {
        // slice of slice: use .ptr member
        emit_.emit("(");
        emit_expr(e->base);
        emit_.emit(").ptr");
    }

    if (!e->full_slice && e->low) {
        emit_.emit(" + (");
        emit_expr(e->low);
        emit_.emit(")");
    }
    emit_.emit("), .len = ");

    if (e->full_slice) {
        if (bty->is_array()) {
            auto* at = static_cast<sem::ArrayType*>(bty);
            emit_.emit(std::to_string(at->count));
        } else {
            emit_.emit("(");
            emit_expr(e->base);
            emit_.emit(").len");
        }
    } else {
        // len = high - low  (inclusive adds 1)
        emit_.emit("(");
        if (e->high) emit_expr(e->high);
        else emit_.emit("0");
        emit_.emit(") - (");
        if (e->low)  emit_expr(e->low);
        else emit_.emit("0");
        emit_.emit(")");
        if (e->inclusive) emit_.emit(" + 1");
    }
    emit_.emit(" })");
}

void CodeGen::emit_field(FieldExpr* e) {
    TypeRef bty = tc_.type_of(e->base);
    // Enum variant access: Direction.UP → Direction::UP
    if (bty && bty->is_enum()) {
        emit_expr(e->base);
        emit_.emit("::" + e->field);
        return;
    }
    emit_expr(e->base);
    // Auto-deref: pointer types use -> in C
    if (bty && bty->is_ptr()) emit_.emit("->");
    else                       emit_.emit(".");
    emit_.emit(e->field);
}

void CodeGen::emit_deref(DerefExpr* e) {
    emit_.emit("(*");
    emit_expr(e->expr);
    emit_.emit(")");
}

void CodeGen::emit_addr(AddrExpr* e) {
    emit_.emit("(&");
    emit_expr(e->expr);
    emit_.emit(")");
}

void CodeGen::emit_cast(CastExpr* e) {
    TypeRef dest = tc_.type_of(e);
    if (e->is_bit_cast) {
        // bit_cast(T)(x) → *reinterpret_cast<const T*>(&(x))
        emit_.emit("(*reinterpret_cast<const ");
        emit_c_type(dest);
        emit_.emit("*>(&(");
        emit_expr(e->expr);
        emit_.emit(")))");
        return;
    }
    emit_.emit("((");
    emit_c_type(dest);
    emit_.emit(")(");
    emit_expr(e->expr);
    emit_.emit("))");
}

void CodeGen::emit_lit(LitExpr* e, TypeRef hint) {
    switch (e->lit_kind) {
        case LitExpr::INT: {
            emit_.emit(static_cast<uint64_t>(e->int_val));
            if (hint && hint->kind == SemanticType::Kind::U64)
                emit_.emit("ULL");
            else if (hint && hint->kind == SemanticType::Kind::U32)
                emit_.emit("U");
        } break;
        case LitExpr::FLOAT: {
            emit_.emit(e->float_val);
            // Default float literal is f32; omit suffix only if explicitly widened to f64
            if (!hint || hint->kind == SemanticType::Kind::F32)
                emit_.emit("f");
        } break;
        case LitExpr::BOOL: {
            emit_.emit(e->bool_val ? "true" : "false");
        } break;
        case LitExpr::NIL: {
            emit_.emit("NULL");
        } break;
        case LitExpr::STRING: {
            // Emit as a plain C string literal "...".
            // std::string implicitly constructs from const char* where needed.
            // Plain literals work correctly for printf/variadic contexts.
            emit_.emit("\"");
            for (char c : e->str_val) {
                switch (c) {
                    case '"':  emit_.emit("\\\""); break;
                    case '\\': emit_.emit("\\\\"); break;
                    case '\n': emit_.emit("\\n");  break;
                    case '\t': emit_.emit("\\t");  break;
                    case '\r': emit_.emit("\\r");  break;
                    default:   emit_.emit(c);      break;
                }
            }
            emit_.emit("\"");
        } break;
    }
}

// ---------------------------------------------------------------------------
// c_safe_name: prefix ZedLang identifiers that clash with C/C++ reserved words
// or well-known stdlib names pulled in by our preamble headers.
// ---------------------------------------------------------------------------
std::string CodeGen::c_safe_name(const std::string& n) {
    static const std::unordered_set<std::string_view> c_reserved = {
        // ---- C keywords ----
        "auto","void","char","short","int","long","float","double",
        "signed","unsigned","const","volatile","restrict",
        "static","extern","register","inline",
        "if","else","switch","case","default",
        "break","continue","goto","return",
        "for","while","do",
        "struct","union","enum","typedef","sizeof",
        // ---- C++ keywords ----
        "class","namespace","template","typename",
        "virtual","override","final","explicit","friend",
        "public","private","protected",
        "new","delete","this","operator",
        "try","catch","throw","noexcept",
        "using","alignof","decltype","nullptr","true","false",
        "constexpr","constinit","consteval","mutable",
        "concept","requires",
        "co_await","co_return","co_yield",
        "export","import","module",
        // alternative operator tokens (valid C++ identifiers in some contexts)
        "and","or","not","xor",
        "bitand","bitor","compl",
        "and_eq","or_eq","xor_eq","not_eq",
        // ---- stdlib names pulled in by our own preamble ----
        // <stdio.h>
        "printf","fprintf","sprintf","snprintf","scanf","sscanf","fscanf",
        "fopen","fclose","fread","fwrite","fgets","fputs","fgetc","fputc",
        "puts","gets","getchar","putchar","perror","rename","remove",
        "stdin","stdout","stderr","EOF","NULL","SEEK_SET","SEEK_CUR","SEEK_END",
        // <stdlib.h>
        "exit","abort","atexit","at_quick_exit","quick_exit",
        "malloc","calloc","realloc","free","aligned_alloc",
        "atoi","atol","atoll","atof","strtol","strtoll","strtoul","strtod","strtof",
        "rand","srand","RAND_MAX",
        "qsort","bsearch",
        "abs","labs","llabs","div","ldiv","lldiv",
        "getenv","system",
        // <string.h> / <strings.h>
        "memcpy","memmove","memset","memcmp","memchr",
        "strlen","strcmp","strncmp","strcpy","strncpy","strcat","strncat",
        "strchr","strrchr","strstr","strtok","strdup",
        // <assert.h>
        "assert",
        // <errno.h>
        "errno",
        // <time.h>
        "time","clock","difftime","mktime","gmtime","localtime","strftime",
        // <math.h>
        "sin","cos","tan","asin","acos","atan","atan2",
        "sqrt","cbrt","pow","exp","log","log2","log10",
        "ceil","floor","round","fabs","fmod","hypot",
        // <iostream> / common std names that leak into global namespace
        "string","vector","list","map","set","pair","tuple",
        "cout","cin","cerr","clog","endl","flush",
        // <stdint.h> / <stdbool.h> macros that compilers may #define
        "bool","TRUE","FALSE",
    };
    if (c_reserved.count(n)) return "_zl_" + n;
    return n;
}

void CodeGen::emit_ident(IdentExpr* e) {
    // Foreign symbols (imported via cimport) must be emitted verbatim —
    // they are C identifiers and must match the header exactly.
    TypeRef ty = tc_.type_of(e);
    if (ty && ty->is_any_foreign()) {
        emit_.emit(e->name);
        return;
    }
    emit_.emit(c_safe_name(e->name));
}

void CodeGen::emit_struct_lit(StructLitExpr* e) {
    if (e->base && e->fields.empty()) {
        // Pure copy: TypeName{ ..base }  →  base  (no-op, just emit base)
        emit_expr(e->base);
        return;
    }
    if (e->base) {
        // Spread update: start from base then override named fields.
        // C99 designated-init cannot do this directly — emit a compound expression:
        //   [&]{ auto _b = base; _b.field = val; ...; return _b; }()   (C++ lambda)
        emit_.emit("[&](){ auto _zed_base = ");
        emit_expr(e->base);
        emit_.emit("; ");
        for (const FieldInit& fi : e->fields) {
            emit_.emit("_zed_base." + fi.name + " = ");
            emit_expr(fi.value);
            emit_.emit("; ");
        }
        emit_.emit("return _zed_base; }()");
        return;
    }
    // Normal struct literal
    emit_.emit("(" + c_safe_name(e->type_name) + "){");
    for (size_t i = 0; i < e->fields.size(); ++i) {
        if (i > 0) emit_.emit(", ");
        emit_.emit("." + e->fields[i].name + " = ");
        emit_expr(e->fields[i].value);
    }
    emit_.emit("}");
}

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------
void CodeGen::emit_c_type(TypeRef t) {
    if (t->is_ptr()) {
        emit_c_type(static_cast<sem::PtrType*>(t)->pointee);
        emit_.emit("*");
    } else if (t->is_slice()) {
        emit_.emit("Slice");   // runtime/runtime.hpp defines the Slice struct
    } else if (t->is_array()) {
        // C arrays are awkward in return/param positions; emit as pointer here.
        // Full array declarations use emit_var_decl instead.
        emit_c_type(static_cast<sem::ArrayType*>(t)->elem);
        emit_.emit("*");
    } else if (t->is_struct()) {
        emit_.emit(c_safe_name(static_cast<sem::StructType*>(t)->name));
    } else if (t->is_enum()) {
        emit_.emit(c_safe_name(static_cast<sem::EnumType*>(t)->name));
    } else if (t->kind == SemanticType::Kind::FOREIGN_NAMED) {
        emit_.emit(static_cast<sem::ForeignNamedType*>(t)->name);
    } else if (t->kind == SemanticType::Kind::FOREIGN) {
        // Anonymous foreign — should be rare in type-position; auto is safest.
        emit_.emit("auto");
    } else if (t->is_proc()) {
        auto* pt = static_cast<sem::ProcType*>(t);
        emit_.emit("std::function<");
        if (pt->return_type) emit_c_type(pt->return_type);
        else emit_.emit("void");
        emit_.emit("(");
        for (size_t i = 0; i < pt->params.size(); ++i) {
            if (i > 0) emit_.emit(", ");
            emit_c_type(pt->params[i].type);
        }
        emit_.emit(")>");
    } else if (t->is_string()) {
        emit_.emit("std::string");
    } else if (t->is_dyn_array()) {
        auto* da = static_cast<sem::DynArrayType*>(t);
        emit_.emit("std::vector<");
        emit_c_type(da->elem);
        emit_.emit(">");
    } else {
        emit_.emit(primitive_c_name(t->kind));
    }
}

void CodeGen::emit_var_decl(TypeRef t, const std::string& name) {
    const std::string safe = c_safe_name(name);
    if (t->is_array()) {
        auto* at = static_cast<sem::ArrayType*>(t);
        emit_c_type(at->elem);
        emit_.emit(" " + safe + "[" + std::to_string(at->count) + "]");
    } else if (t->is_proc()) {
        // Emit as std::function<ret(params)> name
        auto* pt = static_cast<sem::ProcType*>(t);
        emit_.emit("std::function<");
        if (pt->return_type) emit_c_type(pt->return_type);
        else emit_.emit("void");
        emit_.emit("(");
        for (size_t i = 0; i < pt->params.size(); ++i) {
            if (i > 0) emit_.emit(", ");
            emit_c_type(pt->params[i].type);
        }
        emit_.emit(")> " + safe);
    } else {
        emit_c_type(t);
        emit_.emit(" " + safe);
    }
}

std::string CodeGen::primitive_c_name(SemanticType::Kind k) {
    switch (k) {
        case SemanticType::Kind::VOID:  return "void";
        case SemanticType::Kind::BOOL:  return "bool";
        case SemanticType::Kind::I8:    return "int8_t";
        case SemanticType::Kind::I16:   return "int16_t";
        case SemanticType::Kind::I32:   return "int32_t";
        case SemanticType::Kind::I64:   return "int64_t";
        case SemanticType::Kind::U8:    return "uint8_t";
        case SemanticType::Kind::U16:   return "uint16_t";
        case SemanticType::Kind::U32:   return "uint32_t";
        case SemanticType::Kind::U64:   return "uint64_t";
        case SemanticType::Kind::F32:   return "float";
        case SemanticType::Kind::F64:   return "double";
        case SemanticType::Kind::CSTR:  return "const char*";
        case SemanticType::Kind::FOREIGN_NAMED:
            return "void"; // unreachable: handled by emit_c_type before this
        default:                        return "void";
    }
}

std::string CodeGen::op_str(int tok) {
    switch (tok) {
        case TOK_PLUS:    return "+";
        case TOK_MINUS:   return "-";
        case TOK_STAR:    return "*";
        case TOK_SLASH:   return "/";
        case TOK_PERCENT: return "%";
        case TOK_AMP:     return "&";
        case TOK_PIPE:    return "|";
        case TOK_XOR:     return "^"; // binary XOR
        case TOK_SHL:     return "<<";
        case TOK_SHR:     return ">>";
        case TOK_EQ:      return "==";
        case TOK_NEQ:     return "!=";
        case TOK_LT:      return "<";
        case TOK_LEQ:     return "<=";
        case TOK_GT:      return ">";
        case TOK_GEQ:     return ">=";
        case TOK_AND:     return "&&";
        case TOK_OR:      return "||";
        case TOK_NOT:     return "!";
        default:          return "?";
    }
}

// ---------------------------------------------------------------------------
// emit_tuple — emits all elements as a comma-separated list (used in return)
// For general use (e.g. function arguments), not wrapped in braces here.
// ---------------------------------------------------------------------------
void CodeGen::emit_tuple(TupleExpr* e) {
    // Bare tuple — only valid in return context (handled there).
    // If somehow emitted standalone, fall back to first element.
    if (!e->elems.empty()) emit_expr(e->elems[0]);
}

// ---------------------------------------------------------------------------
// emit_array_init — { expr, expr, ... } aggregate initializer
// Emits: {expr0, expr1, ...} — valid as C initializer or compound literal
// ---------------------------------------------------------------------------
void CodeGen::emit_array_init(ArrayInitExpr* e) {
    emit_.emit("{");
    for (size_t i = 0; i < e->elems.size(); ++i) {
        if (i) emit_.emit(", ");
        emit_expr(e->elems[i]);
    }
    emit_.emit("}");
}

// ---------------------------------------------------------------------------
// emit_sizeof — sizeof(T) or sizeof(expr) / alignof(T)
// ---------------------------------------------------------------------------
void CodeGen::emit_sizeof(SizeofExpr* e) {
    emit_.emit(e->is_align ? "alignof(" : "sizeof(");
    if (e->type_arg) {
        emit_c_type(tc_.resolve(e->type_arg));
    } else {
        emit_expr(e->expr_arg);
    }
    emit_.emit(")");
}

// ---------------------------------------------------------------------------
// emit_multi_decl — a, b := foo()
// Emits a C compound-statement block that captures the return struct:
//   { __ret_foo _zed_tmp = foo(); type_a a = _zed_tmp._0; type_b b = _zed_tmp._1; }
// For non-tuple RHS (shouldn't occur after type-check), falls back.
// ---------------------------------------------------------------------------
void CodeGen::emit_multi_decl(MultiDeclStmt* s) {
    TypeRef rhs_ty = tc_.type_of_multi_decl(s);
    if (rhs_ty && rhs_ty->is_tuple()) {
        auto* tt = static_cast<sem::TupleType*>(rhs_ty);
        // Determine the proc name from the RHS call for the struct type name
        std::string ret_struct;
        if (auto* call = dynamic_cast<CallExpr*>(s->rhs)) {
            if (auto* id = dynamic_cast<IdentExpr*>(call->callee))
                ret_struct = "__ret_" + id->name;
        }
        // Emit a uniquely-named temp so the call is evaluated once, then unpack
        // each variable as a flat statement in the enclosing scope (NOT inside
        // a braced block — that would hide the variables from subsequent stmts).
        if (!ret_struct.empty()) {
            // e.g.: __ret_divide _zed_tmp_divide_0_ = divide(10, 3);
            // The counter suffix prevents redefinition when the same proc
            // is called more than once in the same scope.
            std::string tmp = "_zed_tmp_" + ret_struct.substr(7)
                              + "_" + std::to_string(tmp_counter_++) + "_";
            emit_.begin_line(ret_struct + " " + tmp + " = ");
            emit_expr(s->rhs);
            emit_.emit(";\n");
            for (size_t i = 0; i < s->names.size() && i < tt->elems.size(); ++i) {
                if (s->names[i] == "_") continue;
                emit_.emit_indent();
                emit_var_decl(tt->elems[i], s->names[i]);
                emit_.emit(" = " + tmp + "._" + std::to_string(i) + ";\n");
            }
        } else {
            // No struct name (shouldn't happen after type-check); zero-init each var
            for (size_t i = 0; i < s->names.size() && i < tt->elems.size(); ++i) {
                if (s->names[i] == "_") continue;
                emit_.emit_indent();
                emit_var_decl(tt->elems[i], s->names[i]);
                emit_.emit(" = {};\n");
            }
        }
    } else {
        // Single-value fallback — treat like normal decl
        emit_.emit_indent();
        if (rhs_ty) emit_var_decl(rhs_ty, s->names[0]);
        emit_.emit(" = ");
        emit_expr(s->rhs);
        emit_.emit(";\n");
    }
}

// ---------------------------------------------------------------------------
// emit_multi_assign — a, b = foo()
// ---------------------------------------------------------------------------
void CodeGen::emit_multi_assign(MultiAssignStmt* s) {
    TypeRef rhs_ty = tc_.type_of(s->rhs);
    if (rhs_ty && rhs_ty->is_tuple()) {
        auto* tt = static_cast<sem::TupleType*>(rhs_ty);
        std::string ret_struct;
        if (auto* call = dynamic_cast<CallExpr*>(s->rhs)) {
            if (auto* id = dynamic_cast<IdentExpr*>(call->callee))
                ret_struct = "__ret_" + id->name;
        }
        emit_.emit_indent();
        emit_.emit("{ ");
        if (!ret_struct.empty()) {
            emit_.emit(ret_struct + " _zed_tmp_ = ");
            emit_expr(s->rhs);
            emit_.emit("; ");
        }
        for (size_t i = 0; i < s->lvalues.size() && i < tt->elems.size(); ++i) {
            emit_expr(s->lvalues[i]);
            if (!ret_struct.empty())
                emit_.emit(" = _zed_tmp_._" + std::to_string(i));
            emit_.emit("; ");
        }
        emit_.emit("}\n");
    } else {
        emit_.emit_indent();
        emit_expr(s->lvalues[0]);
        emit_.emit(" = ");
        emit_expr(s->rhs);
        emit_.emit(";\n");
    }
}

// ---------------------------------------------------------------------------
// emit_builtin_call
// ---------------------------------------------------------------------------
void CodeGen::emit_builtin_call(BuiltinCallExpr* e) {
    switch (e->builtin_tok) {
        case TOK_KW_LEN: {
            // len(x) — works for arrays, slices, dyn arrays, strings
            TypeRef arg_ty = e->args.empty() ? nullptr : tc_.type_of(e->args[0]);
            if (arg_ty && arg_ty->is_array()) {
                // Compile-time array length
                emit_.emit(std::to_string(static_cast<sem::ArrayType*>(arg_ty)->count));
            } else if (arg_ty && arg_ty->is_dyn_array()) {
                emit_.emit("(");
                emit_expr(e->args[0]);
                emit_.emit(").size()");
            } else if (arg_ty && arg_ty->is_string()) {
                emit_.emit("(");
                emit_expr(e->args[0]);
                emit_.emit(").size()");
            } else {
                // Slice or unknown
                emit_.emit("(");
                emit_expr(e->args[0]);
                emit_.emit(").len");
            }
            break;
        }
        case TOK_KW_CAP: {
            emit_.emit("(");
            emit_expr(e->args[0]);
            emit_.emit(").capacity()");
            break;
        }
        case TOK_KW_APPEND: {
            // append(&arr, val)  →  (arr).emplace_back(val)
            // args[0] is &arr (AddrExpr), args[1] is val
            if (e->args.size() >= 2) {
                // Strip the & to get the array expression
                Expr* arr = e->args[0];
                if (arr->kind() == Expr::ADDR)
                    arr = static_cast<AddrExpr*>(arr)->expr;
                emit_.emit("(");
                emit_expr(arr);
                emit_.emit(").emplace_back(");
                emit_expr(e->args[1]);
                emit_.emit(")");
            }
            break;
        }
        case TOK_KW_RESERVE: {
            // reserve(&x, n) — sets capacity, len stays 0, reserved slots zero-initialized.
            // Delegates to _zed_dyn_reserve() in runtime.hpp.
            Expr* arr = e->args[0];
            if (arr->kind() == Expr::ADDR)
                arr = static_cast<AddrExpr*>(arr)->expr;
            emit_.emit("_zed_dyn_reserve(");
            emit_expr(arr);
            emit_.emit(", ");
            emit_expr(e->args[1]);
            emit_.emit(")");
            break;
        }
        case TOK_KW_CLEAR: {
            Expr* arr = e->args[0];
            if (arr->kind() == Expr::ADDR)
                arr = static_cast<AddrExpr*>(arr)->expr;
            emit_.emit("(");
            emit_expr(arr);
            emit_.emit(").clear()");
            break;
        }
        case TOK_KW_TO_CSTR: {
            // to_cstr(s)  →  (s).c_str()
            emit_.emit("(");
            emit_expr(e->args[0]);
            emit_.emit(").c_str()");
            break;
        }
        case TOK_KW_FROM_CSTR: {
            // from_cstr(cs)  →  std::string(cs)
            emit_.emit("std::string(");
            emit_expr(e->args[0]);
            emit_.emit(")");
            break;
        }
        case TOK_KW_PANIC: {
            // panic(msg)  →  mem_panic(msg)
            emit_.emit("mem_panic(");
            emit_expr(e->args[0]);
            emit_.emit(")");
            break;
        }
        case TOK_KW_FREE: {
            // free(ptr)  →  mem_free(ptr)
            emit_.emit("mem_free(");
            emit_expr(e->args[0]);
            emit_.emit(")");
            break;
        }
        case TOK_KW_COPY: {
            // copy(dst, src)  →  _zed_slice_copy(dst, src)
            // Works for slices and dynamic arrays
            emit_.emit("_zed_slice_copy(");
            emit_expr(e->args[0]);
            emit_.emit(", ");
            emit_expr(e->args[1]);
            emit_.emit(")");
            break;
        }
        case TOK_KW_ENUM_NAME: {
            // enum_name(val)  →  _zed_enum_name_TYPENAME(val)
            // The type checker resolved the arg type; codegen emits a call to
            // a generated helper. We emit a generic stringify via switch inline.
            TypeRef arg_ty = e->args.empty() ? nullptr : tc_.type_of(e->args[0]);
            if (arg_ty && arg_ty->is_enum()) {
                auto* et = static_cast<sem::EnumType*>(arg_ty);
                // Emit an inline switch that maps enum values to name strings
                emit_.emit("([&]() -> const char* { switch((int)(");
                emit_expr(e->args[0]);
                emit_.emit(")) {");
                for (const auto& v : et->variants) {
                    emit_.emit(" case " + std::to_string(v.value)
                               + ": return \"" + v.name + "\";");
                }
                emit_.emit(" default: return \"<unknown>\"; } }())");
            } else {
                emit_.emit("\"<unknown>\"");
            }
            break;
        }
        case TOK_KW_MIN: {
            // min(a, b)  →  ((a) < (b) ? (a) : (b))
            emit_.emit("((");
            emit_expr(e->args[0]);
            emit_.emit(") < (");
            emit_expr(e->args[1]);
            emit_.emit(") ? (");
            emit_expr(e->args[0]);
            emit_.emit(") : (");
            emit_expr(e->args[1]);
            emit_.emit("))");
            break;
        }
        case TOK_KW_MAX: {
            // max(a, b)  →  ((a) > (b) ? (a) : (b))
            emit_.emit("((");
            emit_expr(e->args[0]);
            emit_.emit(") > (");
            emit_expr(e->args[1]);
            emit_.emit(") ? (");
            emit_expr(e->args[0]);
            emit_.emit(") : (");
            emit_expr(e->args[1]);
            emit_.emit("))");
            break;
        }
        case TOK_KW_ABS: {
            // abs(x)  →  ((x) < 0 ? -(x) : (x))
            emit_.emit("((");
            emit_expr(e->args[0]);
            emit_.emit(") < 0 ? -(");
            emit_expr(e->args[0]);
            emit_.emit(") : (");
            emit_expr(e->args[0]);
            emit_.emit("))");
            break;
        }
        case TOK_KW_SWAP: {
            // swap(&a, &b)  →  ({ auto _t = *(a); *(a) = *(b); *(b) = _t; })
            emit_.emit("({ auto _zed_swap_t_ = *(");
            emit_expr(e->args[0]);
            emit_.emit("); *(");
            emit_expr(e->args[0]);
            emit_.emit(") = *(");
            emit_expr(e->args[1]);
            emit_.emit("); *(");
            emit_expr(e->args[1]);
            emit_.emit(") = _zed_swap_t_; })");
            break;
        }
        case TOK_KW_CLAMP: {
            // clamp(v, lo, hi)  →  ((v)<(lo)?(lo):(v)>(hi)?(hi):(v))
            emit_.emit("((");
            emit_expr(e->args[0]);
            emit_.emit(") < (");
            emit_expr(e->args[1]);
            emit_.emit(") ? (");
            emit_expr(e->args[1]);
            emit_.emit(") : (");
            emit_expr(e->args[0]);
            emit_.emit(") > (");
            emit_expr(e->args[2]);
            emit_.emit(") ? (");
            emit_expr(e->args[2]);
            emit_.emit(") : (");
            emit_expr(e->args[0]);
            emit_.emit("))");
            break;
        }
        default:
            emit_.emit("/*unknown_builtin*/");
            break;
    }
}

// ---------------------------------------------------------------------------
// emit_or_return
// val := call() or_return
// Emits a block-expression using GCC/Clang statement-expr, or a temp var.
// Strategy: use a C99 compound statement that evaluates the tuple, checks
// the bool, and either returns or yields the value.
//
// Generated pattern (for single-value T,bool result):
//   ({ auto _or_tmp = CALL; if (!_or_tmp._1) { return {._0={}, ._1=false}; } _or_tmp._0; })
//
// For void return context: just { if (!_or_tmp._1) return; }
// ---------------------------------------------------------------------------
void CodeGen::emit_or_return(OrReturnExpr* e) {
    if (e->else_expr) {
        // or_else DEFAULT:
        // ({ auto _or_tmp_ = CALL; _or_tmp_._1 ? _or_tmp_._0 : DEFAULT; })
        emit_.emit("({ auto _or_tmp_ = ");
        emit_expr(e->inner);
        emit_.emit("; _or_tmp_._1 ? _or_tmp_._0 : (");
        emit_expr(e->else_expr);
        emit_.emit("); })");
        return;
    }

    // or_return: propagate failure
    const std::string& pname = current_proc_name_;
    bool multi_ret = !pname.empty() && emitted_ret_structs_.count("__ret_" + pname);

    emit_.emit("({ auto _or_tmp_ = ");
    emit_expr(e->inner);
    emit_.emit("; if (!_or_tmp_._1) { ");
    if (multi_ret) {
        emit_.emit("return (__ret_" + pname + "){}; ");
    } else {
        emit_.emit("return; ");
    }
    emit_.emit("} _or_tmp_._0; })");
}

// ---------------------------------------------------------------------------
// emit_proc_lit — anonymous proc literal → C++ lambda with [=] capture
// proc(x: i32) -> i32 { return x * 2 }
// emits: [=](int32_t x) -> int32_t { return x * 2; }
// ---------------------------------------------------------------------------
void CodeGen::emit_proc_lit(ProcLitExpr* e) {
    // Build param list from semantic types stored in the type map
    TypeRef proc_ty = tc_.type_of(e);
    auto* pt = proc_ty ? static_cast<sem::ProcType*>(proc_ty) : nullptr;

    // For multi-return lambdas: synthesize a unique struct name so emit_return
    // can produce a properly-typed return value.
    bool has_multi_ret = pt && pt->return_type && pt->return_type->is_tuple();
    std::string lit_name = "";
    if (has_multi_ret) {
        lit_name = "_lit_" + std::to_string(tmp_counter_++) + "_";
    }

    emit_.emit("[=](");
    bool first = true;
    size_t pi = 0;
    for (const ParamGroup& pg : e->params) {
        if (pg.is_vararg_sentinel) continue;
        TypeRef pty = pt ? pt->params[pi].type : nullptr;
        for (const std::string& pname : pg.names) {
            if (!first) emit_.emit(", ");
            if (pty) emit_var_decl(pty, pname);
            else     emit_.emit("auto " + pname);
            first = false;
            pi++;
        }
    }
    if (pt && pt->is_variadic) {
        if (!first) emit_.emit(", ");
        emit_.emit("...");
    }
    emit_.emit(") -> ");
    if (has_multi_ret) {
        emit_.emit("auto");
    } else if (pt && pt->return_type) {
        emit_c_type(pt->return_type);
    } else {
        emit_.emit("void");
    }
    emit_.emit(" {\n");
    emit_.indent();

    // For multi-return: emit a local struct typedef at the top of the lambda
    // body so return statements can use it.
    if (has_multi_ret) {
        auto* tt = static_cast<sem::TupleType*>(pt->return_type);
        const std::string sname = "__ret_" + lit_name;
        emit_.emit_indent();
        emit_.emit("struct " + sname + " { ");
        for (size_t i = 0; i < tt->elems.size(); ++i) {
            emit_var_decl(tt->elems[i], "_" + std::to_string(i));
            emit_.emit("; ");
        }
        emit_.emit("};\n");
        emitted_ret_structs_.insert(sname);
    }

    // Save/restore current_proc_name_ — use synthetic name for multi-return
    std::string saved_name = current_proc_name_;
    auto saved_ret_names = current_proc_return_names_;
    current_proc_name_ = lit_name;
    current_proc_return_names_ = {};

    for (Stmt* st : e->body->stmts) emit_stmt(st);

    current_proc_name_ = saved_name;
    current_proc_return_names_ = saved_ret_names;
    if (has_multi_ret)
        emitted_ret_structs_.erase("__ret_" + lit_name);

    emit_.dedent();
    emit_.emit_indent();
    emit_.emit("}");
}

// ---------------------------------------------------------------------------
// emit_typeid — typeid(T)  →  a compile-time u64 unique to the type.
// Primitive types use their SemanticType::Kind ordinal.
// Named types (struct/enum/foreign) use FNV-1a hash of the type name.
// The value is stable within a program and can be compared in 'when' conditions.
// ---------------------------------------------------------------------------
static uint64_t compute_type_id(TypeRef t) {
    // FNV-1a 64-bit
    uint64_t h = 14695981039346656037ULL;
    auto mix_byte = [&](uint8_t b) {
        h ^= b;
        h *= 1099511628211ULL;
    };
    mix_byte(static_cast<uint8_t>(t->kind));
    // Mix in the name for named types so distinct named types get different IDs.
    const char* name = nullptr;
    if (t->kind == SemanticType::Kind::STRUCT)
        name = static_cast<sem::StructType*>(t)->name.c_str();
    else if (t->kind == SemanticType::Kind::ENUM)
        name = static_cast<sem::EnumType*>(t)->name.c_str();
    else if (t->kind == SemanticType::Kind::FOREIGN_NAMED)
        name = static_cast<sem::ForeignNamedType*>(t)->name.c_str();
    if (name)
        for (const char* p = name; *p; ++p) mix_byte(static_cast<uint8_t>(*p));
    return h;
}

void CodeGen::emit_typeid(TypeIdExpr* e) {
    TypeRef t = tc_.resolve(e->type_arg);
    emit_.emit(std::to_string(compute_type_id(t)) + "ULL");
}

} // namespace ZedLang
