// =============================================================================
// codegen/codegen.cpp
// =============================================================================

#include "../codegen/codegen.hpp"

#include "../frontend/ast.hpp"       // must precede tok_defs.hpp
#include "../frontend/tok_defs.hpp"  // stable TOK_* constants

#include <cassert>

namespace ZedLang {

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
void CodeGen::generate(Program* prog) {
    emit_preamble();
    emit_.blank();
    emit_cimports(prog);

    // For each imported module: emit its cimports, struct typedefs+defs,
    // and proc forward declarations so the generated .cpp is self-contained.
    for (Program* imp : imported_programs_) {
        emit_cimports(imp);
        emit_.comment("--- imported from " + std::string(imp->decls[0]->range.begin.file) + " ---");
        // struct typedefs
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::STRUCT) {
                auto* sd = static_cast<StructDecl*>(d);
                emit_.line("typedef struct " + sd->struct_name +
                           " " + sd->struct_name + ";");
            }
        }
        emit_.blank();
        // struct definitions
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::STRUCT)
                emit_struct_def(static_cast<StructDecl*>(d));
        }
        // proc forward declarations
        emit_.comment("--- Procedure Forward Declarations ---");
        for (Decl* d : imp->decls) {
            if (d->kind() == Decl::PROC)
                emit_proc_decl(static_cast<ProcDecl*>(d));
        }
        emit_.blank();
    }

    emit_forward_decls(prog);
    emit_.blank();
    emit_enum_decls(prog);
    emit_.blank();
    emit_struct_defs(prog);
    emit_.blank();
    emit_global_consts(prog);
    emit_.blank();
    emit_global_vars(prog);
    emit_.blank();
    emit_proc_defs(prog);
}

// ---------------------------------------------------------------------------
// Preamble
// ---------------------------------------------------------------------------
void CodeGen::emit_preamble() {
    emit_.comment("Generated by Zed Lang — DO NOT EDIT !!");
    emit_.line("#include \"runtime.hpp\"");
    emit_.blank();
    emit_.line("#include <stdint.h>");
    emit_.line("#include <stdbool.h>");
}   

void CodeGen::emit_cimports(Program* prog) {
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::CIMPORT) continue;
        auto* ci = static_cast<CImportDecl*>(d);
        emit_.line("#include \"" + ci->path + "\"");
    }
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Forward declarations
// ---------------------------------------------------------------------------
void CodeGen::emit_forward_decls(Program* prog) {
    emit_.comment("--- Forward Declarations ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::STRUCT) {
            auto* sd = static_cast<StructDecl*>(d);
            emit_.line("typedef struct " + sd->struct_name +
                       " " + sd->struct_name + ";");
        }
    }
    emit_.blank();
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::PROC)
            emit_proc_decl(static_cast<ProcDecl*>(d));
    }
}

// ---------------------------------------------------------------------------
// Struct definitions
// ---------------------------------------------------------------------------
void CodeGen::emit_struct_defs(Program* prog) {
    emit_.comment("--- Struct Definitions ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::STRUCT)
            emit_struct_def(static_cast<StructDecl*>(d));
    }
}

void CodeGen::emit_enum_decls(Program* prog) {
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::ENUM_DECL) continue;
        auto* ed = static_cast<EnumDecl*>(d);
        emit_.line("enum class " + ed->enum_name + " : int32_t {");
        emit_.indent();
        int64_t next = 0;
        for (const auto& v : ed->variants) {
            int64_t val = next;
            if (v.value) {
                if (auto* lit = dynamic_cast<LitExpr*>(v.value))
                    if (lit->lit_kind == LitExpr::INT) val = (int64_t)lit->int_val;
            }
            emit_.line(v.name + " = " + std::to_string(val) + ",");
            next = val + 1;
        }
        emit_.dedent();
        emit_.line("};");
        emit_.blank();
    }
}

void CodeGen::emit_struct_def(StructDecl* sd) {
    emit_.emit_indent();
    emit_.emit("struct " + sd->struct_name);
    emit_.open_brace();
    sem::StructType* st = static_cast<sem::StructType*>(
        tc_.sym_ref().lookup_struct(sd->struct_name));
    if (st) {
        for (const auto& f : st->fields) {
            emit_.emit_indent();
            emit_var_decl(f.type, f.name);
            emit_.emit(";\n");
        }
    }
    emit_.close_brace_semi();
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Global constants
// ---------------------------------------------------------------------------

void CodeGen::emit_global_consts(Program *prog) {
    emit_.comment("--- Global Constants ---");
    bool any = false;
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::CONST) continue;
        emit_global_const(static_cast<ConstDecl*>(d));
        any = true;
    }
    if (any) emit_.blank();
}

void CodeGen::emit_global_const(ConstDecl *cd) {
    TypeRef ty = tc_.type_of(cd->value);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        // C constant/enum — emit as auto const
        emit_.emit("const auto " + cd->const_name);
        if (cd->value) { emit_.emit(" = "); emit_expr(cd->value); }
        emit_.emit(";\n");
        return;
    }
    // add 'const' is the type is not already const-qualified (e.g. pointer types, const char*, etc)
    if (!ty->is_cstr()) emit_.emit("const ");
    emit_c_type(ty);
    emit_.emit(" " + cd->const_name);
    if (cd->value) {
        emit_.emit(" = ");
        emit_expr(cd->value);
    }
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Global variables
// ---------------------------------------------------------------------------
void CodeGen::emit_global_vars(Program *prog) {
    emit_.comment("--- Global Variables ---");
    bool any = false;
    for (Decl* d : prog->decls) {
        if (d->kind() != Decl::VAR) continue;
        emit_global_var(static_cast<VarDecl*>(d));
        any = true;
    }
    if (any) emit_.blank();
}

void CodeGen::emit_global_var(VarDecl* vd) {
    TypeRef ty = tc_.type_of_decl(vd);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        // C/foreign typed global: emit the C name if known, else auto-ish
        std::string cname = (ty->kind == SemanticType::Kind::FOREIGN_NAMED)
            ? static_cast<sem::ForeignNamedType*>(ty)->name
            : "auto";
        emit_.emit(cname + " " + vd->var_name);
        if (vd->init) { emit_.emit(" = "); emit_expr(vd->init); }
        else emit_.emit(" = {}");
        emit_.emit(";\n");
        return;
    }
    emit_var_decl(ty, vd->var_name);
    if (vd->init) {
        emit_.emit(" = ");
        emit_expr(vd->init);
    } else if (!ty->is_array()) {
        emit_.emit(" = {}");
    }
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Procedure forward declaration
// ---------------------------------------------------------------------------
void CodeGen::emit_proc_decl(ProcDecl *pd) {
    TypeRef ty = tc_.sym_ref().lookup(pd->proc_name) ?
                 tc_.sym_ref().lookup(pd->proc_name)->type : nullptr;
    if (!ty || !ty->is_proc()) return;
    auto* pt = static_cast<sem::ProcType*>(ty);

    emit_.emit_indent();
    if (pt->return_type) emit_c_type(pt->return_type);
    else emit_.emit("void");
    emit_.emit(" " + pd->proc_name + "(");

    bool first = true;
    for (const auto& p : pt->params) {
        if (!first) emit_.emit(", ");
        emit_var_decl(p.type, p.name);
        first = false;
    }
    if (pt->params.empty()) emit_.emit("void");
    emit_.emit(");\n");
}

// ---------------------------------------------------------------------------
// Procedure definitions
// ---------------------------------------------------------------------------
void CodeGen::emit_proc_defs(Program* prog) {
    emit_.comment("--- Procedure Definitions ---");
    for (Decl* d : prog->decls) {
        if (d->kind() == Decl::PROC)
            emit_proc_def(static_cast<ProcDecl*>(d));
    }
}

void CodeGen::emit_proc_def(ProcDecl* pd) {
    if (!pd->body) return;

    TypeRef ty = tc_.sym_ref().lookup(pd->proc_name) ?
                 tc_.sym_ref().lookup(pd->proc_name)->type : nullptr;
    if (!ty || !ty->is_proc()) return;
    auto* pt = static_cast<sem::ProcType*>(ty);

    // Signature
    if (pt->return_type) emit_c_type(pt->return_type);
    else emit_.emit("void");
    emit_.emit(" " + pd->proc_name + "(");

    bool first = true;
    size_t pi = 0;
    for (const ParamGroup& pg : pd->params) {
        TypeRef pty = pt->params[pi].type;
        for (const std::string& pname : pg.names) {
            if (!first) emit_.emit(", ");
            emit_var_decl(pty, pname);
            first = false;
            pi++;
        }
    }
    if (pt->params.empty()) emit_.emit("void");
    emit_.emit(")");

    emit_block(pd->body, true);
    emit_.blank();
}

// ---------------------------------------------------------------------------
// Statements
// ---------------------------------------------------------------------------
void CodeGen::emit_stmt(Stmt* s) {
    switch (s->kind()) {
        case Stmt::BLOCK:     emit_block(static_cast<BlockStmt*>(s));          break;
        case Stmt::IF:        emit_if(static_cast<IfStmt*>(s));                break;
        case Stmt::LOOP:      emit_loop(static_cast<LoopStmt*>(s));            break;
        case Stmt::RETURN:    emit_return(static_cast<ReturnStmt*>(s));        break;
        case Stmt::ASSIGN:    emit_assign(static_cast<AssignStmt*>(s));        break;
        case Stmt::EXPR:      emit_expr_stmt(static_cast<ExprStmt*>(s));       break;
        case Stmt::DECL_STMT: emit_decl_stmt(static_cast<DeclStmt*>(s));      break;
        case Stmt::BREAK:     emit_.line("break;");                            break;
        case Stmt::CONTINUE:  emit_.line("continue;");                         break;
        case Stmt::BREAK_LABEL: {
            auto* s2 = static_cast<LabeledBreakStmt*>(s);
            emit_.line("goto __break_" + s2->label + ";");
            break;
        }
        case Stmt::CONTINUE_LABEL: {
            auto* s2 = static_cast<LabeledContinueStmt*>(s);
            emit_.line("goto __continue_" + s2->label + ";");
            break;
        }
        case Stmt::FOR_RANGE:      emit_for_range(static_cast<ForRangeStmt*>(s));          break;
        case Stmt::DEFER:          /* deferred — emitted at return/block end */             break;
        case Stmt::MATCH:          emit_match(static_cast<MatchStmt*>(s));                  break;
        case Stmt::WHEN:           emit_when(static_cast<WhenStmt*>(s));                    break;
        case Stmt::COMPOUND_ASSIGN:emit_compound_assign(static_cast<CompoundAssignStmt*>(s)); break;
        case Stmt::INC_DEC:        emit_inc_dec(static_cast<IncDecStmt*>(s));               break;
        case Stmt::HASH_ASSERT:    emit_hash_assert(static_cast<HashAssertStmt*>(s));        break;
    }
}

// Collect defer stmts in immediate scope of block (not nested)
static std::vector<Stmt*> collect_defers(BlockStmt* b) {
    std::vector<Stmt*> defers;
    for (Stmt* s : b->stmts)
        if (s->kind() == Stmt::DEFER)
            defers.push_back(static_cast<DeferStmt*>(s)->inner);
    std::reverse(defers.begin(), defers.end()); // LIFO
    return defers;
}

void CodeGen::emit_block(BlockStmt* b, bool own_braces) {
    if (own_braces) {
        emit_.emit(" {\n");
        emit_.indent();
    }
    auto defers = collect_defers(b);
    bool returned = false;
    for (Stmt* s : b->stmts) {
        if (!defers.empty()) {
            if (s->kind() == Stmt::RETURN) {
                // Flush defers LIFO before the return
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
                returned = true;
            } else if (s->kind() == Stmt::BREAK || s->kind() == Stmt::CONTINUE) {
                // Also flush before break/continue
                for (Stmt* d : defers) {
                    emit_.emit_indent();
                    emit_expr(static_cast<ExprStmt*>(d)->expr);
                    emit_.emit(";\n");
                }
            }
        }
        emit_stmt(s);
    }
    // Fall-through end of block: flush if we didn't already return
    if (!returned) {
        for (Stmt* d : defers) {
            emit_.emit_indent();
            emit_expr(static_cast<ExprStmt*>(d)->expr);
            emit_.emit(";\n");
        }
    }
    if (own_braces) {
        emit_.dedent();
        emit_.emit_indent();
        emit_.emit("}\n");
    }
}

void CodeGen::emit_if(IfStmt* s) {
    emit_.begin_line("if (");
    emit_expr(s->cond);
    emit_.emit(")");
    emit_block(s->then_block, true);

    for (auto& [econd, eblk] : s->else_ifs) {
        emit_.begin_line("else if (");
        emit_expr(econd);
        emit_.emit(")");
        emit_block(eblk, true);
    }

    if (s->else_block) {
        emit_.begin_line("else");
        emit_block(s->else_block, true);
    }
}

// ---------------------------------------------------------------------------
// for_range: for i in lo..<hi { }  →  for (auto i = lo; i < hi; i += step)
// ---------------------------------------------------------------------------
void CodeGen::emit_for_range(ForRangeStmt* s) {
    emit_.begin_line("for (auto " + s->var + " = ");
    emit_expr(s->lo);
    emit_.emit("; " + s->var + (s->inclusive ? " <= " : " < "));
    emit_expr(s->hi);
    emit_.emit("; " + s->var + " += ");
    if (s->step_expr) emit_expr(s->step_expr);
    else emit_.emit("1");
    emit_.emit(")");
    emit_block(s->body, true);
}

// ---------------------------------------------------------------------------
// match:  match val { case X { } case { } }  →  switch(val) { case X: { } break; default: { } }
// ---------------------------------------------------------------------------
void CodeGen::emit_match(MatchStmt* s) {
    emit_.begin_line("switch (");
    emit_expr(s->value);
    emit_.emit(") {\n");
    emit_.indent();
    for (auto& mc : s->cases) {
        if (mc.value) {
            emit_.emit_indent();
            emit_.emit("case ");
            emit_expr(mc.value);
            emit_.emit(":");  // no trailing space — emit_block(true) adds " {"
        } else {
            emit_.begin_line("default:");
        }
        emit_block(mc.body, true);
        emit_.line("break;");
    }
    emit_.dedent();
    emit_.line("}");
}

// ---------------------------------------------------------------------------
// when:  compile-time conditional → emit only the matching branch
// For now we emit #if 0 / #else approach; simplest: emit all branches guarded
// by constexpr if so C++ compiler trims them.
// ---------------------------------------------------------------------------
void CodeGen::emit_when(WhenStmt* s) {
    emit_.begin_line("if constexpr (");
    emit_expr(s->cond);
    emit_.emit(")");
    emit_block(s->then_block, true);
    for (auto& [ec, eb] : s->else_whens) {
        emit_.begin_line("else if constexpr (");
        emit_expr(ec);
        emit_.emit(")");
        emit_block(eb, true);
    }
    if (s->else_block) {
        emit_.begin_line("else");
        emit_block(s->else_block, true);
    }
}

// ---------------------------------------------------------------------------
// compound assign
// ---------------------------------------------------------------------------
void CodeGen::emit_compound_assign(CompoundAssignStmt* s) {
    emit_.emit_indent();
    emit_expr(s->lvalue);
    switch (s->op) {
        case TOK_PLUS:    emit_.emit(" += "); break;
        case TOK_MINUS:   emit_.emit(" -= "); break;
        case TOK_STAR:    emit_.emit(" *= "); break;
        case TOK_SLASH:   emit_.emit(" /= "); break;
        case TOK_PERCENT: emit_.emit(" %= "); break;
        case TOK_AMP:     emit_.emit(" &= "); break;
        case TOK_PIPE:    emit_.emit(" |= "); break;
        case TOK_XOR:     emit_.emit(" ^= "); break;
        default:          emit_.emit(" += "); break;
    }
    emit_expr(s->rhs);
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// inc/dec
// ---------------------------------------------------------------------------
void CodeGen::emit_inc_dec(IncDecStmt* s) {
    emit_.emit_indent();
    emit_expr(s->expr);
    emit_.emit(s->inc ? "++;\n" : "--;\n");
}

// ---------------------------------------------------------------------------
// #assert  →  static_assert(expr, "file:line: #assert failed")
// ---------------------------------------------------------------------------
void CodeGen::emit_hash_assert(HashAssertStmt* s) {
    std::string msg = std::string(s->range.begin.file ? s->range.begin.file : "?")
                    + ":" + std::to_string(s->range.begin.line)
                    + ": #assert failed";
    emit_.emit_indent();
    emit_.emit("static_assert(");
    emit_expr(s->cond);
    emit_.emit(", \"" + msg + "\");\n");
}

// ---------------------------------------------------------------------------
// for { } / for cond { }  (infinite and while-loop forms)
// ---------------------------------------------------------------------------
void CodeGen::emit_loop(LoopStmt* s) {
    // If this loop has a label, emit a C label before the loop, and a
    // __continue_<label> label inside the body suffix for continue support.
    if (!s->label.empty()) {
        emit_.line("// loop label: " + s->label);
    }
    if (s->cond) {
        emit_.begin_line("while (");
        emit_expr(s->cond);
        emit_.emit(")");
    } else {
        emit_.begin_line("for (;;)");
    }
    // Emit the body
    emit_.emit(" {\n");
    emit_.indent();
    for (Stmt* st : s->body->stmts) {
        // Collect/emit defers handled by emit_block; call it directly
        emit_stmt(st);
    }
    if (!s->label.empty()) {
        emit_.line("__continue_" + s->label + ":;");
    }
    emit_.dedent();
    emit_.emit_indent();
    emit_.emit("}\n");
    if (!s->label.empty()) {
        emit_.line("__break_" + s->label + ":;");
    }
}

void CodeGen::emit_return(ReturnStmt* s) {
    if (s->value) {
        emit_.begin_line("return ");
        emit_expr(s->value);
        emit_.emit(";\n");
    } else {
        emit_.line("return;");
    }
}

void CodeGen::emit_assign(AssignStmt* s) {
    emit_.emit_indent();
    emit_expr(s->lvalue);
    emit_.emit(" = ");
    emit_expr_hint(s->rhs, tc_.type_of(s->lvalue));
    emit_.emit(";\n");
}

void CodeGen::emit_expr_stmt(ExprStmt* s) {
    emit_.emit_indent();
    emit_expr(s->expr);
    emit_.emit(";\n");
}

void CodeGen::emit_decl_stmt(DeclStmt* s) {
    switch (s->decl->kind()) {
        case Decl::VAR:   emit_var_decl_local(static_cast<VarDecl*>(s->decl));   break;
        case Decl::CONST: emit_const_decl_local(static_cast<ConstDecl*>(s->decl)); break;
        default: break;
    }
}

void CodeGen::emit_var_decl_local(VarDecl* vd) {
    // '_' discard: evaluate init for side-effects only, emit nothing if no init
    if (vd->var_name == "_") {
        if (vd->init) {
            emit_.emit_indent();
            emit_.emit("(void)(");
            emit_expr(vd->init);
            emit_.emit(");\n");
        }
        return;
    }
    TypeRef ty = tc_.type_of_decl(vd);
    if (!ty) ty = tc_.sym_ref().arena().ty_error();
    emit_.emit_indent();
    if (ty->is_any_foreign()) {
        if (ty->kind == SemanticType::Kind::FOREIGN_NAMED) {
            // C type with known name: emit "TypeName varname = ..."
            const std::string& cname = static_cast<sem::ForeignNamedType*>(ty)->name;
            if (vd->init) {
                emit_.emit(cname + " " + vd->var_name + " = ");
                emit_expr(vd->init);
                emit_.emit(";\n");
            } else {
                emit_.emit(cname + " " + vd->var_name + " = {};" + "\n");
            }
        } else if (vd->init) {
            // Anonymous foreign type (C function return): use auto
            emit_.emit("auto " + vd->var_name + " = ");
            emit_expr(vd->init);
            emit_.emit(";\n");
        } else {
            // Foreign type, no init, no name: zero-init as void*
            emit_.emit("void* " + vd->var_name + " = nullptr;\n");
        }
        return;
    }
    emit_var_decl(ty, vd->var_name);
    if (vd->init) {
        emit_.emit(" = ");
        emit_expr_hint(vd->init, ty);
    } else if (!ty->is_array()) {
        emit_.emit(" = {}");
    }
    emit_.emit(";\n");
}

void CodeGen::emit_const_decl_local(ConstDecl* cd) {
    // Constants become static const local variables in C.
    TypeRef ty = tc_.type_of(cd->value);
    if (ty->is_any_foreign()) {
        // C enum value / macro constant — let the C compiler determine the type.
        emit_.begin_line("static const auto ");
        emit_.emit(cd->const_name + " = ");
        emit_expr(cd->value);
        emit_.emit(";\n");
        return;
    }
    // cstr maps to "const char*" — don't prepend another "const"
    if (ty->is_cstr())
        emit_.begin_line("static ");
    else
        emit_.begin_line("static const ");
    emit_var_decl(ty, cd->const_name);
    emit_.emit(" = ");
    emit_expr(cd->value);
    emit_.emit(";\n");
}

// ---------------------------------------------------------------------------
// Expressions
// ---------------------------------------------------------------------------
void CodeGen::emit_expr(Expr* e) {
    switch (e->kind()) {
        case Expr::BINARY:     emit_binary(static_cast<BinaryExpr*>(e));           break;
        case Expr::UNARY:      emit_unary(static_cast<UnaryExpr*>(e));             break;
        case Expr::CALL:       emit_call(static_cast<CallExpr*>(e));               break;
        case Expr::INDEX:      emit_index(static_cast<IndexExpr*>(e));             break;
        case Expr::SLICE:      emit_slice(static_cast<SliceExpr*>(e));             break;
        case Expr::FIELD:      emit_field(static_cast<FieldExpr*>(e));             break;
        case Expr::DEREF:      emit_deref(static_cast<DerefExpr*>(e));             break;
        case Expr::ADDR:       emit_addr(static_cast<AddrExpr*>(e));               break;
        case Expr::CAST:       emit_cast(static_cast<CastExpr*>(e));               break;
        case Expr::LIT:        emit_lit(static_cast<LitExpr*>(e));                 break;
        case Expr::IDENT:      emit_ident(static_cast<IdentExpr*>(e));             break;
        case Expr::STRUCT_LIT: emit_struct_lit(static_cast<StructLitExpr*>(e));    break;
    }
}

void CodeGen::emit_expr_hint(Expr* e, TypeRef hint) {
    if (e->kind() == Expr::LIT)
        emit_lit(static_cast<LitExpr*>(e), hint);
    else
        emit_expr(e);
}

void CodeGen::emit_binary(BinaryExpr* e) {
    TypeRef operand_ty = tc_.type_of(e->left);
    emit_.emit("(");
    emit_expr_hint(e->left, operand_ty);
    emit_.emit(" " + op_str(e->op) + " ");
    emit_expr_hint(e->right, operand_ty);
    emit_.emit(")");
}

void CodeGen::emit_unary(UnaryExpr* e) {
    emit_.emit("(" + op_str(e->op));
    // Pass the type of the subexpression as a hint so that float literals
    // inside unary minus get the correct suffix: -(0.5f) not -(0.5)
    TypeRef hint = tc_.type_of(e->expr);
    emit_expr_hint(e->expr, hint);
    emit_.emit(")");
}

void CodeGen::emit_call(CallExpr* e) {
    emit_expr(e->callee);
    emit_.emit("(");
    // Look up param types to pass as hints for float literal suffixes
    TypeRef callee_ty = tc_.type_of(e->callee);
    sem::ProcType* pt = (callee_ty && callee_ty->is_proc())
                      ? static_cast<sem::ProcType*>(callee_ty) : nullptr;
    for (size_t i = 0; i < e->args.size(); ++i) {
        if (i > 0) emit_.emit(", ");
        TypeRef hint = (pt && i < pt->params.size()) ? pt->params[i].type : nullptr;
        emit_expr_hint(e->args[i], hint);
    }
    emit_.emit(")");
}

void CodeGen::emit_index(IndexExpr* e) {
    TypeRef bty = tc_.type_of(e->base);

    if (bty->is_slice()) {
        // Slice indexing: SLICE_IDX(ElemType, slice, idx)
        auto* st = static_cast<sem::SliceType*>(bty);
        emit_.emit("SLICE_IDX(");
        emit_c_type(st->elem);
        emit_.emit(", ");
        emit_expr(e->base);
        emit_.emit(", ");
        emit_expr(e->index);
        emit_.emit(")");
    } else {
        // Plain array indexing
        emit_expr(e->base);
        emit_.emit("[");
        emit_expr(e->index);
        emit_.emit("]");
    }
}

void CodeGen::emit_slice(SliceExpr* e) {
    // Produce a Slice struct literal: { .ptr = base + lo, .len = hi - lo }
    TypeRef bty = tc_.type_of(e->base);

    emit_.emit("((Slice){ .ptr = (void*)(");
    if (bty->is_array()) {
        emit_expr(e->base);
    } else {
        // slice of slice: use .ptr member
        emit_.emit("(");
        emit_expr(e->base);
        emit_.emit(").ptr");
    }

    if (!e->full_slice && e->low) {
        emit_.emit(" + (");
        emit_expr(e->low);
        emit_.emit(")");
    }
    emit_.emit("), .len = ");

    if (e->full_slice) {
        if (bty->is_array()) {
            auto* at = static_cast<sem::ArrayType*>(bty);
            emit_.emit(std::to_string(at->count));
        } else {
            emit_.emit("(");
            emit_expr(e->base);
            emit_.emit(").len");
        }
    } else {
        // len = high - low  (inclusive adds 1)
        emit_.emit("(");
        if (e->high) emit_expr(e->high);
        else emit_.emit("0");
        emit_.emit(") - (");
        if (e->low)  emit_expr(e->low);
        else emit_.emit("0");
        emit_.emit(")");
        if (e->inclusive) emit_.emit(" + 1");
    }
    emit_.emit(" })");
}

void CodeGen::emit_field(FieldExpr* e) {
    TypeRef bty = tc_.type_of(e->base);
    // Enum variant access: Direction.UP → Direction::UP
    if (bty && bty->is_enum()) {
        emit_expr(e->base);
        emit_.emit("::" + e->field);
        return;
    }
    emit_expr(e->base);
    // Auto-deref: pointer types use -> in C
    if (bty && bty->is_ptr()) emit_.emit("->");
    else                       emit_.emit(".");
    emit_.emit(e->field);
}

void CodeGen::emit_deref(DerefExpr* e) {
    emit_.emit("(*");
    emit_expr(e->expr);
    emit_.emit(")");
}

void CodeGen::emit_addr(AddrExpr* e) {
    emit_.emit("(&");
    emit_expr(e->expr);
    emit_.emit(")");
}

void CodeGen::emit_cast(CastExpr* e) {
    TypeRef dest = tc_.type_of(e);
    emit_.emit("((");
    emit_c_type(dest);
    emit_.emit(")(");
    emit_expr(e->expr);
    emit_.emit("))");
}

void CodeGen::emit_lit(LitExpr* e, TypeRef hint) {
    switch (e->lit_kind) {
        case LitExpr::INT: {
            emit_.emit(static_cast<uint64_t>(e->int_val));
            if (hint && hint->kind == SemanticType::Kind::U64)
                emit_.emit("ULL");
            else if (hint && hint->kind == SemanticType::Kind::U32)
                emit_.emit("U");
        } break;
        case LitExpr::FLOAT: {
            emit_.emit(e->float_val);
            // Default float literal is f32; omit suffix only if explicitly widened to f64
            if (!hint || hint->kind == SemanticType::Kind::F32)
                emit_.emit("f");
        } break;
        case LitExpr::BOOL: {
            emit_.emit(e->bool_val ? "true" : "false");
        } break;
        case LitExpr::NIL: {
            emit_.emit("NULL");
        } break;
        case LitExpr::STRING: {
            // Emit a C string literal with minimal escaping.
            emit_.emit('"');
            for (char c : e->str_val) {
                switch (c) {
                    case '"':  emit_.emit("\\\""); break;
                    case '\\': emit_.emit("\\\\"); break;
                    case '\n': emit_.emit("\\n");  break;
                    case '\t': emit_.emit("\\t");  break;
                    case '\r': emit_.emit("\\r");  break;
                    default:   emit_.emit(c);      break;
                }
            }
            emit_.emit('"');
        } break;
    }
}

void CodeGen::emit_ident(IdentExpr* e) {
    emit_.emit(e->name);
}

void CodeGen::emit_struct_lit(StructLitExpr* e) {
    if (e->base && e->fields.empty()) {
        // Pure copy: TypeName{ ..base }  →  base  (no-op, just emit base)
        emit_expr(e->base);
        return;
    }
    if (e->base) {
        // Spread update: start from base then override named fields.
        // C99 designated-init cannot do this directly — emit a compound expression:
        //   [&]{ auto _b = base; _b.field = val; ...; return _b; }()   (C++ lambda)
        emit_.emit("[&](){ auto _zed_base = ");
        emit_expr(e->base);
        emit_.emit("; ");
        for (const FieldInit& fi : e->fields) {
            emit_.emit("_zed_base." + fi.name + " = ");
            emit_expr(fi.value);
            emit_.emit("; ");
        }
        emit_.emit("return _zed_base; }()");
        return;
    }
    // Normal struct literal
    emit_.emit("(" + e->type_name + "){");
    for (size_t i = 0; i < e->fields.size(); ++i) {
        if (i > 0) emit_.emit(", ");
        emit_.emit("." + e->fields[i].name + " = ");
        emit_expr(e->fields[i].value);
    }
    emit_.emit("}");
}

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------
void CodeGen::emit_c_type(TypeRef t) {
    if (t->is_ptr()) {
        emit_c_type(static_cast<sem::PtrType*>(t)->pointee);
        emit_.emit("*");
    } else if (t->is_slice()) {
        emit_.emit("Slice");   // runtime/runtime.hpp defines the Slice struct
    } else if (t->is_array()) {
        // C arrays are awkward in return/param positions; emit as pointer here.
        // Full array declarations use emit_var_decl instead.
        emit_c_type(static_cast<sem::ArrayType*>(t)->elem);
        emit_.emit("*");
    } else if (t->is_struct()) {
        emit_.emit(static_cast<sem::StructType*>(t)->name);
    } else if (t->is_enum()) {
        emit_.emit(static_cast<sem::EnumType*>(t)->name);
    } else if (t->kind == SemanticType::Kind::FOREIGN_NAMED) {
        emit_.emit(static_cast<sem::ForeignNamedType*>(t)->name);
    } else if (t->kind == SemanticType::Kind::FOREIGN) {
        // Anonymous foreign — should be rare in type-position; auto is safest.
        emit_.emit("auto");
    } else if (t->is_proc()) {
        // Emit as a std::function-style type alias or raw function pointer.
        // For variable declarations, emit_var_decl handles the full pointer form.
        // In other positions (e.g. cast targets) emit a simplified void*.
        emit_.emit("void*");
    } else {
        emit_.emit(primitive_c_name(t->kind));
    }
}

void CodeGen::emit_var_decl(TypeRef t, const std::string& name) {
    if (t->is_array()) {
        auto* at = static_cast<sem::ArrayType*>(t);
        emit_c_type(at->elem);
        emit_.emit(" " + name + "[" + std::to_string(at->count) + "]");
    } else if (t->is_proc()) {
        // Emit as C function pointer:  ret (*name)(ParamType, ...)
        auto* pt = static_cast<sem::ProcType*>(t);
        if (pt->return_type) emit_c_type(pt->return_type);
        else emit_.emit("void");
        emit_.emit(" (*" + name + ")(");
        for (size_t i = 0; i < pt->params.size(); ++i) {
            if (i > 0) emit_.emit(", ");
            emit_c_type(pt->params[i].type);
        }
        emit_.emit(")");
    } else {
        emit_c_type(t);
        emit_.emit(" " + name);
    }
}

std::string CodeGen::primitive_c_name(SemanticType::Kind k) {
    switch (k) {
        case SemanticType::Kind::VOID:  return "void";
        case SemanticType::Kind::BOOL:  return "bool";
        case SemanticType::Kind::I8:    return "int8_t";
        case SemanticType::Kind::I16:   return "int16_t";
        case SemanticType::Kind::I32:   return "int32_t";
        case SemanticType::Kind::I64:   return "int64_t";
        case SemanticType::Kind::U8:    return "uint8_t";
        case SemanticType::Kind::U16:   return "uint16_t";
        case SemanticType::Kind::U32:   return "uint32_t";
        case SemanticType::Kind::U64:   return "uint64_t";
        case SemanticType::Kind::F32:   return "float";
        case SemanticType::Kind::F64:   return "double";
        case SemanticType::Kind::CSTR:  return "const char*";
        case SemanticType::Kind::FOREIGN_NAMED:
            return "void"; // unreachable: handled by emit_c_type before this
        default:                        return "void";
    }
}

std::string CodeGen::op_str(int tok) {
    switch (tok) {
        case TOK_PLUS:    return "+";
        case TOK_MINUS:   return "-";
        case TOK_STAR:    return "*";
        case TOK_SLASH:   return "/";
        case TOK_PERCENT: return "%";
        case TOK_AMP:     return "&";
        case TOK_PIPE:    return "|";
        case TOK_XOR:     return "^"; // binary XOR
        case TOK_SHL:     return "<<";
        case TOK_SHR:     return ">>";
        case TOK_EQ:      return "==";
        case TOK_NEQ:     return "!=";
        case TOK_LT:      return "<";
        case TOK_LEQ:     return "<=";
        case TOK_GT:      return ">";
        case TOK_GEQ:     return ">=";
        case TOK_AND:     return "&&";
        case TOK_OR:      return "||";
        case TOK_NOT:     return "!";
        default:          return "?";
    }
}

} // namespace ZedLang
